Description of cleanDrugTherapyNamings
Home > Code > pdm > helperfunctions > cleanDrugTherapyNamings.m
cleanDrugTherapyNamings
PURPOSE
useful only for pre-REDCAP update datasets
SYNOPSIS
function out = cleanDrugTherapyNamings(str_array)
DESCRIPTION
 useful only for pre-REDCAP update datasets
 inputs: array, output: array with cleaned drugtherapy names
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
patientCommitment Insights about the amount of FEV1 recordings per patient across the study
plotPatientProfiles plot a profile of each measures for each patient over the whole enrolment period
visualisePatientSummary
SOURCE CODE
% useful only for pre-REDCAP update datasets
% inputs: array, output: array with cleaned drugtherapy names
function out = cleanDrugTherapyNamings(str_array)
    fprintf('Clean drug therapy namings.\nInitial drug therapy list:\n')
    disp(categorical(unique(str_array)));
    out = replace(str_array,["symkevi","Symkevi Modulator"],"Symkevi");
    out = replace(out,["Modulator VX-445,tezacaftor,ivacaftor"...
        ,"Kaftrio + Kalydeco","VX115 Study Trikafta open label",...
        "triple therapy open label trial","Trikafta + Kalydeco", ...
        "Triple therapy","Kaftrio","kaftrio","Trikaftor","Trikafta", ...
        ],"Triple Therapy");
    out = replace(out,"ivacaftor","Ivacaftor");
    fprintf('Cleaned drug therapy list:\n')
    Drug_therapy = categorical(unique(out)); Count = countcats(categorical(out));
    disp(table(Drug_therapy,Count))
end