Description of am4AddToMean
Home > Code > smartcare > am4AddToMean.m
am4AddToMean
PURPOSE
am4AddToMean - add an underlying curve to the meancurve (sumsq, sum and count)
SYNOPSIS
function [meancurvesumsq, meancurvesum, meancurvecount] = am4AddToMean(meancurvesumsq, meancurvesum, meancurvecount,amIntrCube, offset, currinter, min_offset, max_offset, align_wind, nmeasures)
DESCRIPTION
 am4AddToMean - add an underlying curve to the meancurve (sumsq, sum and count)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
am4AlignCurves am4AlignCurves = function to align measurement curves prior to intervention
am4VisualiseAlignmentDetail am4VisualiseAlignmentDetail - creates a plot of horizontal bars showing
test_objfcn_script
SOURCE CODE
function [meancurvesumsq, meancurvesum, meancurvecount] = am4AddToMean(meancurvesumsq, meancurvesum, meancurvecount, ...
    amIntrCube, offset, currinter, min_offset, max_offset, align_wind, nmeasures)
% am4AddToMean - add an underlying curve to the meancurve (sumsq, sum and count)
for m = 1:nmeasures
    for i = 1:(max_offset + align_wind - 1 - offset)
        if ~isnan(amIntrCube(currinter, max_offset + align_wind - i, m))
            meancurvesumsq(max_offset + align_wind - offset - i, m) = meancurvesumsq(max_offset + align_wind - offset - i, m) + (amIntrCube(currinter, max_offset + align_wind - i, m) ^ 2);
            meancurvesum(max_offset + align_wind - offset - i, m)   = meancurvesum(max_offset + align_wind - offset - i, m)   +  amIntrCube(currinter, max_offset + align_wind - i, m);
            meancurvecount(max_offset + align_wind - offset - i, m) = meancurvecount(max_offset + align_wind - offset - i, m) + 1;
        end
    end
end
end