Description of amEMPlotAndSaveAlignedCurves
Home > Code > smartcare > amEMPlotAndSaveAlignedCurves.m
amEMPlotAndSaveAlignedCurves
PURPOSE
amEMPlotAndSaveAlignedCurves - plots the curves pre and post alignment for
SYNOPSIS
function amEMPlotAndSaveAlignedCurves(profile_pre, meancurvemean, meancurvecount, meancurvestd, offsets,measures, max_points, min_offset, max_offset, align_wind, nmeasures, run_type, ex_start, sigmamethod, plotname, plotsubfolder)
DESCRIPTION
 amEMPlotAndSaveAlignedCurves - plots the curves pre and post alignment for
 each measure, and the histogram of offsets
CROSS-REFERENCE INFORMATION
This function calls:
amEMPlotAlignedCurve amEMPlotAlignedCurve - plots a latent curve for a given measure (pre and post alignment)
amEMPlotOffsetHistogram amEMPlotOffsetHistogram - plots the histogram of offsets for a given
createFigureAndPanel createFigureAndPanel - creates a figure with a ui panel and returns
savePlotInDir savePlots - saves the figure to png and svp file types in the specified
This function is called by:
amEMMCPlotAndSaveAlignedCurves amEMMCPlotAndSaveAlignedCurves - wrapper around the
runAlignmentModelEM
runAlignmentModelEMFcn function to run the alignment model (EM version) given a set of run
runAlignmentModelEMFcnFEV1Split function to run the alignment model (EM version) given a set of run
SOURCE CODE
function amEMPlotAndSaveAlignedCurves(profile_pre, meancurvemean, meancurvecount, meancurvestd, offsets, ...
    measures, max_points, min_offset, max_offset, align_wind, nmeasures, run_type, ex_start, sigmamethod, plotname, plotsubfolder)
% amEMPlotAndSaveAlignedCurves - plots the curves pre and post alignment for
% each measure, and the histogram of offsets
if (nmeasures + 1) <= 9
    plotsacross = 3;
else
    plotsacross = 4;
end
plotsdown = ceil((nmeasures + 1) / plotsacross);
plottitle = sprintf('%s - %s', plotname, run_type);
anchor = 1; % latent curve is to be anchored on the plot (right side at min_offset)
[f, p] = createFigureAndPanel(plottitle, 'portrait', 'a4');
for m = 1:nmeasures
    subplottitle = measures.DisplayName{m};
    ax = subplot(plotsdown,plotsacross,m,'Parent',p);
    amEMPlotAlignedCurve(ax, profile_pre(:, m), meancurvemean(:, m), meancurvecount(:, m), meancurvestd(:, m), ...
        measures(m, :), max_points, min_offset, max_offset, align_wind, run_type, ex_start, sigmamethod, anchor, subplottitle);
end
ax = subplot(plotsdown, plotsacross, nmeasures + 1, 'Parent', p);
amEMPlotOffsetHistogram(ax, offsets, max_offset);
% save plot
savePlotInDir(f, plottitle, plotsubfolder);
close(f);
end