Description of appendDeletedRows
Home > Code > smartcare > appendDeletedRows.m
appendDeletedRows
PURPOSE
appendDeletedRows - appends a set of deleted measurement rows to the
SYNOPSIS
function [deltable] = appendDeletedRows(delrows, deltable, reason)
DESCRIPTION
 appendDeletedRows - appends a set of deleted measurement rows to the
 deleted table along with the reason for the deletion
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
addBreatheRowsForMeasure addBreatheRowsForMeasure - adds the rows to physdata (and
correctClimbDataAnomalies correctClimbDataAnomalies - looks at various outliers in the measures
findAndDeleteAnomalousMeasures findAndDeleteAnomalousMeasures - finds anomalous values and deletes them
loadclimbdata
SOURCE CODE
function [deltable] = appendDeletedRows(delrows, deltable, reason)
% appendDeletedRows - appends a set of deleted measurement rows to the
% deleted table along with the reason for the deletion
delrows.Reason(:) = reason;
deltable = [deltable; delrows];
end