Description of calcMeanAndStd
Home > Code > smartcare > calcMeanAndStd.m
calcMeanAndStd
PURPOSE
am4CalcMeanAndStd - recalc meancurvemean and meancurvestd arrays
SYNOPSIS
function [meancurvemean, meancurvestd] = calcMeanAndStd(meancurvesumsq, meancurvesum, meancurvecount, min_offset, max_offset, align_wind)
DESCRIPTION
 am4CalcMeanAndStd - recalc meancurvemean and meancurvestd arrays
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
am4AlignCurves am4AlignCurves = function to align measurement curves prior to intervention
am4VisualiseAlignmentDetail am4VisualiseAlignmentDetail - creates a plot of horizontal bars showing
amEMAlignCurves amEMAlignCurves - function to align measurement curves prior to intervention
amEMVisualiseAlignmentDetail amEMVisualiseAlignmentDetail - creates a plot of horizontal bars showing
SOURCE CODE
function [meancurvemean, meancurvestd] = calcMeanAndStd(meancurvesumsq, meancurvesum, meancurvecount, min_offset, max_offset, align_wind)
% am4CalcMeanAndStd - recalc meancurvemean and meancurvestd arrays
% recalculate mean curve and std by day
meancurvemean = meancurvesum ./ meancurvecount;
meancurvestd  = (abs((meancurvesumsq ./ meancurvecount) - (meancurvemean .* meancurvemean))) .^ 0.5;
if min_offset > 0
    meancurvemean((max_offset + align_wind - min_offset): (max_offset + align_wind - 1),:) = 0;
    meancurvestd((max_offset + align_wind - min_offset): (max_offset + align_wind - 1),:)  = 0;
end
end