Description of calcExStartFromTestLabels
Home > Code > smartcare > calcExStartFromTestLabels.m
calcExStartFromTestLabels
PURPOSE
calcExStartFromTestLabels - derives the ex_start date for a given
SYNOPSIS
function ex_start = calcExStartFromTestLabels(amLabelledInterventions, amInterventions,overall_pdoffset, max_offset, plotsubfolder, modelrun, countthresh)
DESCRIPTION
 calcExStartFromTestLabels - derives the ex_start date for a given
 alignment model run from the test labels.
CROSS-REFERENCE INFORMATION
This function calls:
calcVotesArray calcVotesArray - calculates the true and false votes across the labelled test data
createFigureAndPanel createFigureAndPanel - creates a figure with a ui panel and returns
savePlotInDir savePlots - saves the figure to png and svp file types in the specified
setBaseDir setBaseDir - sets the root directory for the code, plots, data files etc
This function is called by:
amEMMCCalcExStartsFromTestLabels amEMMCCalcExStartsFromTestLabels - wrapper around
runModelUtilityFunctions
SOURCE CODE
function ex_start = calcExStartFromTestLabels(amLabelledInterventions, amInterventions, ...
    overall_pdoffset, max_offset, plotsubfolder, modelrun, countthresh)
% calcExStartFromTestLabels - derives the ex_start date for a given
% alignment model run from the test labels.
plotsacross = 1;
plotsdown = 6;
%countthresh = 5;
name1 = sprintf('%s - Ex_Start from TestLabels', modelrun);
[f1, p1] = createFigureAndPanel(name1, 'Portrait', 'A4');
%ax1 = gobjects(plotsacross * plotsdown,1);
[truevotes, falsevotes] = calcVotesArray(amLabelledInterventions, amInterventions, ...
                                overall_pdoffset, max_offset);
sumtrue = sum(truevotes);
sumfalse = sum(falsevotes);
sumtrue((sumtrue + sumfalse) < countthresh) = 0;
%countthresh = max(sumtrue) * 0.2;
%sumtrue(sumtrue < countthresh) = 0;
days = (-1 * (size(truevotes,2)):-1);
thisplot = 1;
ax1(thisplot) = subplot(plotsdown, plotsacross, thisplot, 'Parent',p1);
b = bar(ax1(thisplot), days, sumtrue, 0.75, 'FaceColor', 'green', 'EdgeColor', 'black');
title(sprintf('ExStart true votes by day - All %d Examples', size(amInterventions, 1)));
thisplot = thisplot + 1;
ax1(thisplot) = subplot(plotsdown, plotsacross, thisplot, 'Parent',p1);
b = bar(ax1(thisplot), days, sumfalse, 0.75, 'FaceColor', 'green', 'EdgeColor', 'black');
title(sprintf('ExStart false votes by day - All %d Examples', size(amInterventions, 1)));
thisplot = thisplot + 1;
ax1(thisplot) = subplot(plotsdown, plotsacross, thisplot, 'Parent',p1);
b = bar(ax1(thisplot), days, sumtrue ./ (sumtrue + sumfalse), 0.75, 'FaceColor', 'blue', 'EdgeColor', 'black');
title(sprintf('ExStart true proportion votes by day - All %d Examples', size(amInterventions, 1)));
idx = amLabelledInterventions.IncludeInTestSet == 'Y';
[truevotes, falsevotes] = calcVotesArray(amLabelledInterventions(idx, :), amInterventions(idx, :), ...
                                overall_pdoffset(idx, :), max_offset);
sumtrue = sum(truevotes);
sumfalse = sum(falsevotes);
sumtrue((sumtrue + sumfalse) < countthresh) = 0;
%countthresh = max(sumtrue) * 0.2;
%sumtrue(sumtrue < countthresh) = 0;
days = (-1 * (size(truevotes,2)):-1);
thisplot = thisplot + 1;
ax1(thisplot) = subplot(plotsdown, plotsacross, thisplot, 'Parent',p1);
b = bar(ax1(thisplot), days, sumtrue, 0.75, 'FaceColor', 'green', 'EdgeColor', 'black');
title(sprintf('ExStart true votes by day (%d Test Set examples)', size(amInterventions(idx,:),1)));
thisplot = thisplot + 1;
ax1(thisplot) = subplot(plotsdown, plotsacross, thisplot, 'Parent',p1);
b = bar(ax1(thisplot), days, sumfalse, 0.75, 'FaceColor', 'green', 'EdgeColor', 'black');
title(sprintf('ExStart false votes by day (%d Test Set examples)', size(amInterventions(idx,:),1)));
thisplot = thisplot + 1;
ax1(thisplot) = subplot(plotsdown, plotsacross, thisplot, 'Parent',p1);
b = bar(ax1(thisplot), days, sumtrue ./ (sumtrue + sumfalse), 0.75, 'FaceColor', 'blue', 'EdgeColor', 'black');
title(sprintf('ExStart true proportion votes by day (%d Test Set examples)', size(amInterventions(idx,:),1)));
basedir = setBaseDir();
%plotsubfolder = sprintf('Plots/%s', subfolder);
savePlotInDir(f1, name1, plotsubfolder);
close(f1);
if sum(sumtrue) == 0
    ex_start = -1;
else
    [~, maxpt] = max(sumtrue ./ (sumtrue + sumfalse));
    ex_start = -1 * (size(truevotes,2)) - 1 + maxpt;
end
end