Description of calculateSigmaNormalisation
Home > Code > smartcare > calculateSigmaNormalisation.m
calculateSigmaNormalisation
PURPOSE
calculateSigmaNormalisation - populates an array of ninterventions by
SYNOPSIS
function [normstd] = calculateSigmaNormalisation(amInterventions, measures, demographicstable, ninterventions, nmeasures, sigmamethod, study)
DESCRIPTION
 calculateSigmaNormalisation - populates an array of ninterventions by
 nmeasures with the multiplicative normalisation (sigma) values
CROSS-REFERENCE INFORMATION
This function calls:
getColumnForMeasure getColumnForMeasure - returns the column name from physdata for the
getExNormMeasures getExNormMeasures - returns an array of measure display names that need
This function is called by:
createIntrNormDataCube create the array with the normalised data for each intervention
runAlignmentModelEMMCRecoveryFcn runs the alignment model (EM version) given a set of run parameters.
runFastAlignmentModelEMMCRecoveryFcn fast version with 1 plot (typical profile) + alignment result matfile
runAlignmentModelEM
runAlignmentModelEMFcn function to run the alignment model (EM version) given a set of run
runAlignmentModelEMFcnFEV1Split function to run the alignment model (EM version) given a set of run
runAlignmentModelEMMCFcn runs the alignment model (EM version) given a set of run parameters.
runAlignmentModelEMMCFcnSplit function to run the alignment model (EM version) given a set of run
SOURCE CODE
function [normstd] = calculateSigmaNormalisation(amInterventions, measures, demographicstable, ninterventions, nmeasures, sigmamethod, study)
% calculateSigmaNormalisation - populates an array of ninterventions by
% nmeasures with the multiplicative normalisation (sigma) values
exnormmeas   = getExNormMeasures(study);
normstd = zeros(ninterventions, nmeasures);
for i = 1:ninterventions
    for m = 1:nmeasures
        % this code block is for measures that should be normalised
        if ~ismember(measures.DisplayName(m), exnormmeas)
            if sigmamethod == 1
                normstd(i,m) = measures.AlignWindStd(m);
            elseif sigmamethod == 2
                normstd(i,m) = measures.OverallStd(m);
            elseif (sigmamethod == 3) || (sigmamethod == 4)
                scid = amInterventions.SmartCareID(i);
                column = getColumnForMeasure(measures.Name{m});
                ddcolumn = sprintf('Fun_%s',column);
                if size(find(demographicstable.SmartCareID == scid & ismember(demographicstable.RecordingType, measures.Name{m})),1) == 0
                    fprintf('Intervention %d: Could not find std for patient %d and measure %d so using overall std for measure instead\n', i, scid, m);
                    normstd(i,m) = measures.OverallStd(m);
                else
                    normstd(i,m) = demographicstable{demographicstable.SmartCareID == scid & ismember(demographicstable.RecordingType, measures.Name{m}),{ddcolumn}}(2);
                    if normstd(i,m) == 0
                        fprintf('Intervention %d: Zero std for patient %d and measure %d so using overall std for measure instead\n', i, scid, m);
                        normstd(i,m) = measures.OverallStd(m);
                    end
                end
            else
                %shouldn't get here...
                fprintf('Should never get to this branch of code\n');
            end
        else
            % for measures excluded from normalisation, set to unit
            % variance
            normstd(i,m) = 1;
        end
    end
end
end