Description of createFigureAndPanelForPaper
Home > Code > smartcare > createFigureAndPanelForPaper.m
createFigureAndPanelForPaper
PURPOSE
createFigureAndPanel - creates a figure with a ui panel and returns
SYNOPSIS
function [f, p] = createFigureAndPanelForPaper(name, widthinch, heightinch)
DESCRIPTION
 createFigureAndPanel - creates a figure with a ui panel and returns
 handles to each
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
amEMMCPlotSuperimposedAlignedCurvesForPaper3Recovery amEMMCPlotSuperimposedAlignedCurves3 - wrapper around the
amEMMCPlotVariablesVsLatentCurveSetForPaperRecovery amEMMCPlotVariablesVsLatentCurveSet - compact plots of various variables
amEMMCPlotHistOfTimeSinceLastExacerbation amEMMCPlotHistogramTimeSinceLastExacerbation - function to plot
amEMMCPlotHistogramOfTimeToTreatForPaper amEMMCPlotHistogramOfTimeToTreatForPaper - plots a historgram of the time
amEMMCPlotInterventionsByLatentCurveSetForPaper amEMMCPlotInterventionsByLatentCurveSetForPaper - plots interventions and
amEMMCPlotSuperimposedAlignedCurvesForPaper amEMMCPlotSuperimposedAlignedCurves - wrapper around the
amEMMCPlotSuperimposedAlignedCurvesForPaper2 amEMMCPlotSuperimposedAlignedCurves2 - wrapper around the
amEMMCPlotSuperimposedAlignedCurvesForPaper3 amEMMCPlotSuperimposedAlignedCurves3 - wrapper around the
amEMMCPlotVariablesVsLatentCurveSetForPaper amEMMCPlotVariablesVsLatentCurveSet - compact plots of various variables
calcDaysInPeriodWithHistogram calcDaysInPeriodWithHistogram - calculate the days on IV for pre and during
calcExFrequencyByDT calcExFrequencyByDT - function to analyse the frequency of exacerbations
calcNbrCFTRModInPeriod calcNbrCFTRModInPeriod - calculates how many patients started CFTR
calcPrePostNbrCFTRModInPeriod calcNbrCFTRModInPeriod - calculates how many patients started CFTR
loadbreatheclinicalREDCapdata loads Breathe clinical data from REDCap database
loadbreatheclinicaldatanew loads Breathe clinical data for each patient
plotAlignedCurveComparison
plotLCSetByHospital plotLCSetByHospital - plots barcharts of Latent Curve set by hospital
plotNbrIntrByPatient plotNbrIntrByPatient - plots bar chart of number of interventions by
plotPointsWithLFitLoop plotPointsWithLFitLoop loops over all relevant patients and produces
testLayoutScript
visualiseExacerbationForPaperFcn visualiseExacerbationForPaperFcn - plots measures around an exacerbation
visualiseExacerbationForPaperFcn2 visualiseExacerbationForPaperFcn - plots measures around an exacerbation
visualiseExacerbationForPaperFcn3 visualiseExacerbationForPaperFcn3 - plots measures around an exacerbation
visualiseMeasuresFcn visualiseMeasuresFcn - plots clinical and home measures
visualiseMeasuresForPaperFcn visualiseMeasuresForPaperFcn - plots clinical and home measures
visualiseMeasuresForPaperFcn2 visualiseMeasuresForPaperFcn2 - plots clinical and home measures
SOURCE CODE
function [f, p] = createFigureAndPanelForPaper(name, widthinch, heightinch)
% createFigureAndPanel - creates a figure with a ui panel and returns
% handles to each
f = figure('Name', name, 'Units', 'inches', 'Position', [2, 4, widthinch, heightinch], 'Color', 'white');
%set(gcf, 'Units', 'normalized', 'OuterPosition', [0.65, 0, 0.35, 0.92], 'PaperOrientation', orientation, ...
%    'PaperUnits', 'normalized','PaperPosition',[0, 0, 1, 1], 'PaperType', pagesize);
p = uipanel('Parent',f,'BorderType','none', 'BackgroundColor', 'white', 'Units', 'normalized');
p.Title = name;
p.TitlePosition = 'centertop';
p.FontSize = 8;
p.FontWeight = 'bold';
end