Description of createBreatheClinicalTables
Home > Code > smartcare > createBreatheClinicalTables.m
createBreatheClinicalTables
PURPOSE
createBreatheClinicalTables - creates all the clinical
SYNOPSIS
function [brPatient, brDrugTherapy, brAdmissions, brAntibiotics, brClinicVisits, brOtherVisits, brUnplannedContact,brCRP, brPFT, brMicrobiology, brHghtWght, brEndStudy] = createBreatheClinicalTables(nrows)
DESCRIPTION
 createBreatheClinicalTables - creates all the clinical
 tables for project breathe, with nrows rows in each
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
createBreatheClinicalSpreadsheetsByPatient-DS iMac 201611 (2)
createBreatheClinicalSpreadsheetsByPatient
loadBreatheClinDataForPatient-DS iMac 201611 (2) loadBreatheClinDataForPatient - ingests the clinical data for a given
loadBreatheClinDataForPatient loadBreatheClinDataForPatient - ingests the clinical data for a given
loadbreatheclinicaldata
loadbreatheclinicaldatanew loads Breathe clinical data for each patient
SOURCE CODE
function [brPatient, brDrugTherapy, brAdmissions, brAntibiotics, brClinicVisits, brOtherVisits, brUnplannedContact, ...
    brCRP, brPFT, brMicrobiology, brHghtWght, brEndStudy] = createBreatheClinicalTables(nrows)
% createBreatheClinicalTables - creates all the clinical
% tables for project breathe, with nrows rows in each
brPatient      = table('Size',[nrows 24], ...
    'VariableTypes', {'double',          'cell',       'cell',          'datetime',           'datetime',     'datetime', ...
                      'datetime',        'datetime',   'double',        'cell',               'double',       'double',  ...
                      'double',          'double',     'cell',          'cell',               'cell',    ...
                      'cell',            'double',     'double',        'double',             'double',       ...
                      'double',          'double'}, ...
    'VariableNames', {'ID',              'Hospital',   'StudyNumber',   'StudyDate',          'Prior6Mnth',   'Post6Mnth', ...
                      'PatClinDate',     'DOB',        'Age',           'Sex',                'Height',       'Weight',  ...
                      'PredictedFEV1',   'FEV1SetAs',  'StudyEmail',    'CFGene1',            'CFGene2', ...
                      'GeneralComments', 'CalcAge',    'CalcAgeExact',  'CalcPredictedFEV1',  'CalcPredictedFEV1OrigAge', ...
                      'CalcFEV1SetAs',   'CalcFEV1SetAsOrigAge'});
brDrugTherapy = table('Size',[nrows 6], ...
    'VariableTypes', {'double', 'cell',     'cell',        'datetime',             'cell',            'cell'}, ...
    'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'DrugTherapyStartDate', 'DrugTherapyType', 'DrugTherapyComment',});
brAdmissions   = table('Size',[nrows 6], ...
    'VariableTypes', {'double', 'cell',     'cell',        'datetime', 'datetime',  'cell'}, ...
    'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'Admitted', 'Discharge', 'Comments'});
brAntibiotics  = table('Size',[nrows 9], ...
    'VariableTypes', {'double', 'cell',     'cell',        'cell',           'cell',  'cell',     'datetime',   'datetime', 'cell'}, ...
    'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'AntibioticName', 'Route', 'HomeIV_s', 'StartDate',  'StopDate', 'Comments'});
brClinicVisits = table('Size',[nrows 6], ...
    'VariableTypes', {'double', 'cell',     'cell',        'datetime',       'cell',     'cell'}, ...
    'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'AttendanceDate', 'Location', 'Comments'});
brOtherVisits  = table('Size',[nrows 6], ...
    'VariableTypes', {'double', 'cell',     'cell',        'datetime',       'cell',      'cell'}, ...
    'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'AttendanceDate', 'VisitType', 'Comments'});
brUnplannedContact  = table('Size',[nrows 6], ...
    'VariableTypes', {'double', 'cell',     'cell',        'datetime',    'cell',          'cell'}, ...
    'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'ContactDate', 'TypeOfContact', 'Comments'});
brPFT          = table('Size',[nrows 9], ...
    'VariableTypes', {'double', 'cell',     'cell',        'datetime',         'double', 'cell',  'double', 'double',    'cell'}, ...
    'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'LungFunctionDate', 'FEV1',   'Units', 'FEV1_',  'CalcFEV1_', 'Comments'});
brCRP          = table('Size',[nrows 9], ...
    'VariableTypes', {'double', 'cell',     'cell',        'datetime', 'cell',  'cell',  'cell',               'double',       'cell'}, ...
    'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'CRPDate',  'Level', 'Units', 'PatientAntibiotics', 'NumericLevel', 'Comments'});
brMicrobiology = table('Size',[nrows 7], ...
    'VariableTypes', {'double', 'cell',     'cell',        'cell',         'datetime',         'cell',        'cell'}, ...
    'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'Microbiology', 'DateMicrobiology', 'NameIfOther', 'Comments'});
brHghtWght = table('Size',[nrows 10], ...
    'VariableTypes', {'double', 'cell',     'cell',        'datetime', 'double', 'double',   'double', 'double',   'double',  'cell'}, ...
    'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'MeasDate', 'Height', 'H_ZScore', 'Weight', 'W_ZScore', 'BMI',     'Comments'});
brEndStudy     = table('Size',[nrows 4], ...
    'VariableTypes', {'double', 'cell',     'cell',        'cell'}, ...
    'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'EndOfStudyReason'});
end