Description of createBreatheMeasuresTable
Home > Code > smartcare > createBreatheMeasuresTable.m
createBreatheMeasuresTable
PURPOSE
createBreatheMeasuresTable - creates a copy of the physdata
SYNOPSIS
function [brphysdata] = createBreatheMeasuresTable(nrows)
DESCRIPTION
 createBreatheMeasuresTable - creates a copy of the physdata
 measures table for project breathe with <nrows> blank rows in
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
addBreatheRowsForMeasure addBreatheRowsForMeasure - adds the rows to physdata (and
loadbreathedata 1st Breathe data processing step and analysis from raw measurements
loadbreathemeasurementdata 1st Breathe data processing step and analysis from raw measurements
SOURCE CODE
function [brphysdata] = createBreatheMeasuresTable(nrows)
% createBreatheMeasuresTable - creates a copy of the physdata
% measures table for project breathe with <nrows> blank rows in
brphysdata      = table('Size',[nrows 17], ...
    'VariableTypes', {'double',        'double',        'double',       'cell',       'cell',          'cell',          'datetime', ...
                      'double',        'double',        'double',       'double',     'double',        'double', ...
                      'double',        'double',        'double',       'double'}, ...
    'VariableNames', {'SmartCareID',   'ScaledDateNum', 'DateNum',      'UserName',   'RecordingType', 'CaptureType',   'Date_TimeRecorded', ...
                      'FEV',           'WeightInKg',    'O2Saturation', 'Pulse_BPM_', 'Temp_degC_',    'Calories', ...
                      'Rating',        'Sleep',         'HasCondition', 'CalcFEV1_'});
%brphysdata      = table('Size',[nrows 22], ...
%    'VariableTypes', {'double',          'double',        'double',       'cell',         'cell',          'datetime', ...
%                      'double',          'double',        'double',       'double',       'double',        'double', ...
%                      'double',          'double',        'double',       'double',       'double',        'double', ...
%                      'double',          'double',        'double',       'double'}, ...
%   'VariableNames', {'SmartCareID',     'ScaledDateNum', 'DateNum',      'UserName',     'RecordingType', 'Date_TimeRecorded', ...
%                      'FEV1',            'FEV2575',       'FEV075',       'FEV1DivFEV6',  'FEV6',          'WeightInKg', ...
%                      'O2Saturation',    'Pulse_BPM_',    'RestingHR',    'Temp_degC_',   'Calories',      'Rating', ...
%                      'TotalMinAsleep',  'TotalMinAwake', 'HasColdOrFlu', 'HasHayfever'});
end