Description of createAndSaveClimbFEVPlots
Home > Code > smartcare > createAndSaveClimbFEVPlots.m
createAndSaveClimbFEVPlots
PURPOSE
createAndSaveFEVPlots - function to create plots of FEV home vs clinical
SYNOPSIS
function createAndSaveClimbFEVPlots(patientlist, pmeasuresfev, pclinicalfev, pstudydate,mindays, maxdays, plotsacross, plotsdown, plotsperpage, subfolder, filenameprefix)
DESCRIPTION
 createAndSaveFEVPlots - function to create plots of FEV home vs clinical
 measures and save results to file
CROSS-REFERENCE INFORMATION
This function calls:
createFigureAndPanel createFigureAndPanel - creates a figure with a ui panel and returns
savePlotInDir savePlots - saves the figure to png and svp file types in the specified
setYDisplayRange setYDisplayRange - function to scale y axis of plots appropriately
This function is called by:
checkClimbCalculatedClinicalVsHomeFEV1Measures
SOURCE CODE
function createAndSaveClimbFEVPlots(patientlist, pmeasuresfev, pclinicalfev, pstudydate, ...
    mindays, maxdays, plotsacross, plotsdown, plotsperpage, subfolder, filenameprefix)
% createAndSaveFEVPlots - function to create plots of FEV home vs clinical
% measures and save results to file
npages = ceil(size(patientlist, 1) / plotsperpage);
page = 1;
imagefilename = sprintf('%s - Page %2d of %2d', filenameprefix, page, npages);
[f, p] = createFigureAndPanel(imagefilename, 'Portrait', 'a4');
for i = 1:size(patientlist, 1)
    scid = patientlist(i);
    hospital = pstudydate.Hospital{pstudydate.SmartCareID == scid};
    % get home weight measures just for current patient
    pmeasures = pmeasuresfev(pmeasuresfev.SmartCareID == scid,:);
    % get clinical weight measures just for current patient
    pclinical = pclinicalfev(pclinicalfev.SmartCareID == scid,:);
    % get study start and end dates just for current patient
    studystart = pstudydate.ScaledDateNum(i);
    studyend = studystart + 183;
    % store min and max for patient (and handle case where there are no
    % clinical measures
    if size(pmeasures, 1) > 0
        minpmfev = min(pmeasures.FEV1_);
        maxpmfev = max(pmeasures.FEV1_);
    else
        minpmfev = 50;
        maxpmfev = 50;
    end
    if size(pclinical,1) > 0
        minpcfev = min(pclinical.FEV1_);
        maxpcfev = max(pclinical.FEV1_);
    else
        minpcfev = minpmfev;
        maxpcfev = maxpmfev;
    end
    % plot FEV1 measures
    ax = subplot(plotsdown, plotsacross, i - (page - 1) * plotsperpage, 'Parent', p);
    hold on;
    plot(ax, pmeasures.ScaledDateNum,pmeasures.FEV1_,'y-o',...
        'LineWidth',1,...
        'MarkerSize',3,...
        'MarkerEdgeColor','b',...
        'MarkerFaceColor','g');
    plot(ax, pclinical.ScaledDateNum,pclinical.FEV1_,'c-o',...
        'LineWidth',1,...
        'MarkerSize',3,...
        'MarkerEdgeColor','m',...
        'MarkerFaceColor','w');
    xl = [mindays maxdays];
    xlim(xl);
    rangelimit = 0.5;
    yl = setYDisplayRange(0, max(maxpcfev, maxpmfev), rangelimit);
    ylim(yl);
    title(ax, sprintf('Patient %3d (%s)',scid, hospital));
    % add study start and end as vertical lines
    line(ax, [studystart studystart], yl, 'Color', 'g', 'LineStyle', '-', 'LineWidth', 1);
    line(ax,  [studyend studyend],     yl, 'Color', 'g', 'LineStyle', '-', 'LineWidth', 1);
    hold off
    fprintf('Row %3d, Patient %3d\n', ...
        i, scid);
    % create a new page as necessary
    if round((i)/plotsperpage) == (i)/plotsperpage
        savePlotInDir(f, imagefilename, subfolder);
        close(f);
        page = page + 1;
        imagefilename = sprintf('%s - Page %2d of %2d', filenameprefix, page, npages);
        [f, p] = createFigureAndPanel(imagefilename, 'Portrait', 'a4');
        fprintf('Next Page\n');
    end
end
if exist('f', 'var')
    savePlotInDir(f, imagefilename, subfolder);
    close(f);
end
end