Description of findAndDeleteAnomalousMeasures
Home > Code > smartcare > findAndDeleteAnomalousMeasures.m
findAndDeleteAnomalousMeasures
PURPOSE
findAndDeleteAnomalousMeasures - finds anomalous values and deletes them
SYNOPSIS
function [brphysdata, brphysdata_deleted] = findAndDeleteAnomalousMeasures(brphysdata, brphysdata_deleted, recordingtype, lowerthresh, upperthresh)
DESCRIPTION
 findAndDeleteAnomalousMeasures - finds anomalous values and deletes them
CROSS-REFERENCE INFORMATION
This function calls:
appendDeletedRows appendDeletedRows - appends a set of deleted measurement rows to the
getColumnForMeasure getColumnForMeasure - returns the column name from physdata for the
This function is called by:
correctBreatheDataAnomalies correctBreatheDataAnomalies - looks at various outliers in the measures
SOURCE CODE
function [brphysdata, brphysdata_deleted] = findAndDeleteAnomalousMeasures(brphysdata, brphysdata_deleted, recordingtype, lowerthresh, upperthresh)
% findAndDeleteAnomalousMeasures - finds anomalous values and deletes them
outputcolname = getColumnForMeasure(recordingtype);
idx1 = ismember(brphysdata.RecordingType, recordingtype);
idx2 = table2array(brphysdata(:, {outputcolname})) < lowerthresh | table2array(brphysdata(:, {outputcolname})) > upperthresh;
idx  = idx1 & idx2;
fprintf('Removing %4d %25s entries < %7.2f or > %7.2f\n', sum(idx), recordingtype, lowerthresh, upperthresh);
brphysdata_deleted = appendDeletedRows(brphysdata(idx, :), brphysdata_deleted, {'Anomalous Value'});
brphysdata(idx, :) = [];
end