Description of getInvertedMeasures
Home > Code > smartcare > getInvertedMeasures.m
getInvertedMeasures
PURPOSE
getInvertedMeasures - returns an array of measure display names that need
SYNOPSIS
function [invmeasarray] = getInvertedMeasures(study)
DESCRIPTION
 getInvertedMeasures - returns an array of measure display names that need
 to be inverted
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
exploreInterventions explores the list of interventions
plotTypicalProfileAndTimeToResponse plot typical profile and compute time to response
RcreateNormalisedIntrDatacube createNormalisedIntrDatacube - creates the normalised data cube by
amEMMCPlotSuperimposedAlignedCurvesForPaper3Recovery amEMMCPlotSuperimposedAlignedCurves3 - wrapper around the
calculateMuNormalisationRecovery populates an array of ninterventions by nmeasures with the additive
amEMMCPlotSuperimposedAlignedCurves amEMMCPlotSuperimposedAlignedCurves - wrapper around the
amEMMCPlotSuperimposedAlignedCurvesForPaper amEMMCPlotSuperimposedAlignedCurves - wrapper around the
amEMMCPlotSuperimposedAlignedCurvesForPaper3 amEMMCPlotSuperimposedAlignedCurves3 - wrapper around the
calculateMuNormalisation calculateMuNormalisation - - populates an array of ninterventions by
plotAlignedCurveComparison
visualiseExacerbationForPaperFcn3 visualiseExacerbationForPaperFcn3 - plots measures around an exacerbation
visualiseMeasuresForPaperFcn2 visualiseMeasuresForPaperFcn2 - plots clinical and home measures
SOURCE CODE
function [invmeasarray] = getInvertedMeasures(study)
% getInvertedMeasures - returns an array of measure display names that need
% to be inverted
if ismember(study, {'SC'})
    invmeasarray = {'PulseRate'};
elseif ismember(study, {'BR'})
    invmeasarray = {'PulseRate', 'MinsAwake', 'RestingHR', 'Temperature'};
elseif ismember(study, {'CL'})
    invmeasarray = {'PulseRate', 'RespiratoryRate', 'SleepDisturbance', 'Temperature'};
else
    invmeasarray = {'PulseRate'};
end
end