Description of getLCSortOrder
Home > Code > smartcare > getLCSortOrder.m
getLCSortOrder
PURPOSE
getLCSortOrder - returns the latent curve sets sorted from largest
SYNOPSIS
function lcsort = getLCSortOrder(amInterventions, nlatentcurves)
DESCRIPTION
 getLCSortOrder - returns the latent curve sets sorted from largest
 population to smallest
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
amEMMCPlotSuperimposedAlignedCurvesForPaper3Recovery amEMMCPlotSuperimposedAlignedCurves3 - wrapper around the
amEMMCPlotVariablesVsLatentCurveSetForPaperRecovery amEMMCPlotVariablesVsLatentCurveSet - compact plots of various variables
amEMMCPlotSuperimposedAlignedCurvesForPaper amEMMCPlotSuperimposedAlignedCurves - wrapper around the
amEMMCPlotSuperimposedAlignedCurvesForPaper2 amEMMCPlotSuperimposedAlignedCurves2 - wrapper around the
amEMMCPlotSuperimposedAlignedCurvesForPaper3 amEMMCPlotSuperimposedAlignedCurves3 - wrapper around the
amEMMCPlotVariablesVsLatentCurveSetForPaper amEMMCPlotVariablesVsLatentCurveSet - compact plots of various variables
SOURCE CODE
function lcsort = getLCSortOrder(amInterventions, nlatentcurves)
% getLCSortOrder - returns the latent curve sets sorted from largest
% population to smallest
lccount = zeros(nlatentcurves, 1);
for l = 1:nlatentcurves
    lccount(l) = sum(amInterventions.LatentCurve == l);
end
[~, lcsort] = sort(lccount, 'descend');
end