Description of getLatestBreatheMeasDate
Home > Code > smartcare > getLatestBreatheMeasDate.m
getLatestBreatheMeasDate
PURPOSE
getLatestBreatheMeasDate - convenience function to centralise getting the
SYNOPSIS
function [measdate] = getLatestBreatheMeasDate()
DESCRIPTION
 getLatestBreatheMeasDate - convenience function to centralise getting the
 latest breathe measurement filename date suffixes
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
patientCommitment Insights about the amount of FEV1 recordings per patient across the study
loadbreathedata 1st Breathe data processing step and analysis from raw measurements
loadbreathemeasurementdata 1st Breathe data processing step and analysis from raw measurements
SOURCE CODE
function [measdate] = getLatestBreatheMeasDate()
% getLatestBreatheMeasDate - convenience function to centralise getting the
% latest breathe measurement filename date suffixes
measdate     = '20210726';
end