Description of getMeasureOverallMinMax
Home > Code > smartcare > getMeasureOverallMinMax.m
getMeasureOverallMinMax
PURPOSE
getMeasureMinMax - returns the min and max value for a measure across all
SYNOPSIS
function [measuremin, measuremax] = getMeasureOverallMinMax(demographicstable, measure)
DESCRIPTION
 getMeasureMinMax - returns the min and max value for a measure across all
 patients and days
CROSS-REFERENCE INFORMATION
This function calls:
getColumnForMeasure getColumnForMeasure - returns the column name from physdata for the
This function is called by:
amEMMCPreprocessMeasuresRecovery amEMMCPreprocessMeasures - 1) select a set of measures, 2) filter
amEMMCPreprocessMeasures amEMMCPreprocessMeasures - various bits of pre-processing to measures table
amEMPreprocessMeasures amEMPreprocessMeasures - various bits of pre-processing to measures table
SOURCE CODE
function [measuremin, measuremax] = getMeasureOverallMinMax(demographicstable, measure)
% getMeasureMinMax - returns the min and max value for a measure across all
% patients and days
column = getColumnForMeasure(measure);
ddcolumn = sprintf('Fun_%s',column);
tempmin = demographicstable{ismember(demographicstable.RecordingType, measure),{ddcolumn}}(:,3);
tempmax = demographicstable{ismember(demographicstable.RecordingType, measure),{ddcolumn}}(:,4);
measuremin = min(tempmin(~isnan(tempmin)));
measuremax = max(tempmax(~isnan(tempmax)));
end