Description of getPatientOffsets
Home > Code > smartcare > getPatientOffsets.m
getPatientOffsets
PURPOSE
gets the patient offset table
SYNOPSIS
function [patientoffsettable] = getPatientOffsets(physdata)
DESCRIPTION
 gets the patient offset table
 Convenience function to return offsets for each
 patient 0 i.e the difference between the actual date and the scaled date
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
plotPatientProfiles plot a profile of each measures for each patient over the whole enrolment period
createListOfInterventionsRecovery creates the list of distinct Antiobiotic treatments in a structure to be used by the alignment model
checkBreatheClinicalVsHomeFEV1Measures
checkBreatheClinicalVsHomeWeightMeasures
checkCalculatedClinicalVsHomeFEV1Measures
checkClimbCalculatedClinicalVsHomeFEV1Measures
checkClinicalVsHomeFEV1Measures
checkClinicalVsHomeFEV1Measures_Telemed
checkClinicalVsHomeWeightMeasures
checkDatesAdmissionsVsAntibiotics
checkDatesClinicVisitsVsCRPNew
checkDatesClinicVisitsVsPFTNew
checkDatesIVTreatmentsVsMeasurementDate
checkDatesIVTreatmentsVsPatientStudyDate
checkStudyDateVsFirstMeasurementDate
createClinMeasPredExcelDataByPatient
createListOfInterventions creates the list of distinct IV Antiobiotic treatments in a structure to be used by the alignment model
createMeasuresHeatmapSorted createMeasuresHeatmapSorted - creates the Patient/Measures
createMeasuresHeatmapSortedForPaper createMeasuresHeatmapSortedForPaper - creates the Patient/Measures
createMeasuresHeatmapWithStudyPeriod createMeasuresHeatmapWithStudyPeriod - creates the Patient/Measures
createMeasuresHeatmapWithStudyPeriodByHospital createMeasuresHeatmapWithStudyPeriod - creates the Patient/Measures
extractClinicalAndHomeFEV1Measures
visualiseExacerbationTimeline
visualiseMeasures
visualiseMeasuresFcn visualiseMeasuresFcn - plots clinical and home measures
visualiseMeasuresForPaperFcn visualiseMeasuresForPaperFcn - plots clinical and home measures
visualiseMeasuresForPaperFcn2 visualiseMeasuresForPaperFcn2 - plots clinical and home measures
visualisePatientSummary
SOURCE CODE
function [patientoffsettable] = getPatientOffsets(physdata)
% gets the patient offset table
% Convenience function to return offsets for each
% patient 0 i.e the difference between the actual date and the scaled date
physdata.PatientOffset =  physdata.DateNum - physdata.ScaledDateNum;
patientoffsettable = unique(physdata(:,{'SmartCareID','PatientOffset'}));
end