Description of getRawDataFilenamesForStudy
Home > Code > smartcare > getRawDataFilenamesForStudy.m
getRawDataFilenamesForStudy
PURPOSE
getRawDataFilenamesForStudy - return filenames for raw data files for
SYNOPSIS
function [datamatfile, clinicalmatfile, demographicsmatfile] = getRawDataFilenamesForStudy(study)
DESCRIPTION
 getRawDataFilenamesForStudy - return filenames for raw data files for
 measurement and clinical data
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
analyseFEV1Variability analysis of FEV1 variability with moving average manually implemented
analyseFEV1Variability_old analysis of FEV1 variability with smoothing spline and movmean
plotFEV1profiles plot FEV1 profiles with modulators and treatments
plotMonthlyBehaviour plots monthly evolution of biomarkers
createHeatMapInterventions plot heatmap with #measurements per day for all interventions
exploreInterventions explores the list of interventions
patientCommitment insights about the amount of FEV1 recordings per patient across the study
patientDemographics create an excel with current BR patient demographics
plotPatientProfiles plot a profile of each measures for each patient over the whole enrolment period
checkBreatheTreatmentsVsSelectMeasuresPost creates list of oral & IV treatments for recovery study
createAlignmentModelInputsRecovery creates the inputs for the model
relateInferredClassesToPatientFeatures analyse the relation between patient characteristics and subset of interventions
runSpecificInterventions run a model with a manually selected subset of interventions
EmemLungFunctionComparison
JosieQuery
PrePostAnalysisPatientEligibilityScript
calcClinicalInfoForPaper
checkBreatheClinicalVsHomeFEV1Measures
checkBreatheClinicalVsHomeWeightMeasures
checkBreatheTreatmentsVsSelectMeasuresPrior creates list of oral & IV treatments
checkClimbCalculatedClinicalVsHomeFEV1Measures
checkClinicalVsHomeWeightMeasures
checkDatesAdmissionsVsAntibiotics
checkDatesClinicVisitsVsCRPNew
checkDatesClinicVisitsVsPFTNew
checkDatesIVTreatmentsVsMeasurementDate
checkDatesIVTreatmentsVsPatientStudyDate
checkIVTreatmentsVsMeasuresPriorNew creates list of oral & IV treatments
checkStudyDateVsFirstMeasurementDate
createAlignmentModelInputs creates the inputs for the model
createBreatheInterimCheckpointStats
createBreathePrePostStats
createClinMeasPredExcelDataByPatient
createDataExportForREDCap createDataExportForREDCap.m - a script that takes current clinical data
extractClinicalAndHomeFEV1Measures
runAlignmentModelEMMCFcnSplit function to run the alignment model (EM version) given a set of run
runModelUtilityFunctionsEMMC
runPlotsForPaperEMMC
visualiseExacerbationTimeline
visualiseMeasures
visualisePatientSummary
SOURCE CODE
function [datamatfile, clinicalmatfile, demographicsmatfile] = getRawDataFilenamesForStudy(study)
% getRawDataFilenamesForStudy - return filenames for raw data files for
% measurement and clinical data
demographicsmatfile = sprintf('%sdatademographicsbypatient.mat', study);
if ismember(study, 'SC')
    clinicalmatfile = 'clinicaldata.mat';
    datamatfile     = 'smartcaredata.mat';
elseif ismember(study, 'TM')
    clinicalmatfile = 'telemedclinicaldata.mat';
    datamatfile     = 'telemeddata.mat';
elseif ismember(study, 'CL')
    clinicalmatfile = 'climbclinicaldata.mat';
    datamatfile     = 'climbdata.mat';
elseif ismember(study, 'BR')
    clinicalmatfile = 'breatheclinicaldata.mat';
    datamatfile     = 'breathedata.mat';
else
    fprintf('Invalid study\n');
    clinicalmatfile = 'unknown';
    datamatfile     = 'unknown';
    return;
end
end