Description of loadPatientMasterFileForAllHosp
Home > Code > smartcare > loadPatientMasterFileForAllHosp.m
loadPatientMasterFileForAllHosp
PURPOSE
loadPatientMasterFileForAllHosp - loads and concatenates the patient
SYNOPSIS
function [patientmaster] = loadPatientMasterFileForAllHosp(study, hosprows)
DESCRIPTION
 loadPatientMasterFileForAllHosp - loads and concatenates the patient
 master files for all hospitals
CROSS-REFERENCE INFORMATION
This function calls:
getLatestBreatheDatesForHosp getLatestBreatheDatesForHosp - convenience function to centralise getting the
loadPatientMasterFileForHosp loadPatientMasterFileForHosp - convenience function to load the patient
printPatientMasterStats printPatientMasterStats - prints numbers enrolled, number consented,
This function is called by:
loadbreatheclinicaldatanew loads Breathe clinical data for each patient
SOURCE CODE
function [patientmaster] = loadPatientMasterFileForAllHosp(study, hosprows)
% loadPatientMasterFileForAllHosp - loads and concatenates the patient
% master files for all hospitals
patientmaster = [];
for h = 1:size(hosprows, 1)
    [~, hosppatmastdate] = getLatestBreatheDatesForHosp(hosprows.Acronym{h});
    [hosppatmaster] = loadPatientMasterFileForHosp(study, hosprows(h, :), hosppatmastdate);
    patientmaster = [patientmaster; hosppatmaster];
    fprintf('For %s hospital\n', hosprows.Name{h});
    printPatientMasterStats(hosppatmaster);
    fprintf('\n');
end
fprintf('Overall\n');
printPatientMasterStats(patientmaster);
fprintf('\n');
end