Description of loadAndHarmoniseClinVars
Home > Code > smartcare > loadAndHarmoniseClinVars.m
loadAndHarmoniseClinVars
PURPOSE
loadAndHarmoniseClinVars - loads clinical variables and standardises
SYNOPSIS
function [cdPatient, cdDrugTherapy, cdMicrobiology, cdAntibiotics, cdAdmissions, cdPFT, cdCRP,cdClinicVisits, cdOtherVisits, cdEndStudy, cdHghtWght, cdMedications, cdNewMeds, cdUnplannedContact]= loadAndHarmoniseClinVars(clinicalmatfile, subfolder, study)
DESCRIPTION
 loadAndHarmoniseClinVars - loads clinical variables and standardises
 their naming
CROSS-REFERENCE INFORMATION
This function calls:
setBaseDir setBaseDir - sets the root directory for the code, plots, data files etc
This function is called by:
patientDemographics create an excel with current BR patient demographics
plotPatientProfiles plot a profile of each measures for each patient over the whole enrolment period
checkBreatheTreatmentsVsSelectMeasuresPost creates list of oral & IV treatments for recovery study
createAlignmentModelInputsRecovery creates the inputs for the model
relateInferredClassesToPatientFeatures analyse the relation between patient characteristics and subset of interventions
runSpecificInterventions run a model with a manually selected subset of interventions
EmemLungFunctionComparison
JosieQuery
PrePostAnalysisPatientEligibilityScript
calcClinicalInfoForPaper
checkBreatheClinicalVsHomeFEV1Measures
checkBreatheClinicalVsHomeWeightMeasures
checkBreatheTreatmentsVsSelectMeasuresPrior creates list of oral & IV treatments
checkClimbCalculatedClinicalVsHomeFEV1Measures
checkClinicalVsHomeWeightMeasures
checkDatesAdmissionsVsAntibiotics
checkDatesClinicVisitsVsCRPNew
checkDatesClinicVisitsVsPFTNew
checkDatesIVTreatmentsVsMeasurementDate
checkDatesIVTreatmentsVsPatientStudyDate
checkIVTreatmentsVsMeasuresPriorNew creates list of oral & IV treatments
checkStudyDateVsFirstMeasurementDate
createAlignmentModelInputs creates the inputs for the model
createBreatheInterimCheckpointStats
createBreathePrePostStats
createClinMeasPredExcelDataByPatient
createDataExportForREDCap createDataExportForREDCap.m - a script that takes current clinical data
extractClinicalAndHomeFEV1Measures
runAlignmentModelEMMCFcnSplit function to run the alignment model (EM version) given a set of run
runModelUtilityFunctionsEMMC
runPlotsForPaperEMMC
visualiseExacerbationTimeline
visualiseMeasures
visualisePatientSummary
SOURCE CODE
function [cdPatient, cdDrugTherapy, cdMicrobiology, cdAntibiotics, cdAdmissions, cdPFT, cdCRP, ...
    cdClinicVisits, cdOtherVisits, cdEndStudy, cdHghtWght, cdMedications, cdNewMeds, cdUnplannedContact] ...
            = loadAndHarmoniseClinVars(clinicalmatfile, subfolder, study)
% loadAndHarmoniseClinVars - loads clinical variables and standardises
% their naming
tic
basedir = setBaseDir();
fprintf('Loading %s Clinical data\n', study);
if ismember(study, 'SC')
    load(fullfile(basedir, subfolder, clinicalmatfile), 'cdPatient', 'cdMicrobiology', 'cdClinicVisits', 'cdPFT', 'cdAdmissions', ...
        'cdAntibiotics', 'cdCRP', 'cdEndStudy', 'cdOtherVisits', 'cdMedications', 'cdNewMeds');
    cdDrugTherapy      = [];
    cdHghtWght         = [];
    cdUnplannedContact = [];
elseif ismember(study, 'TM')
    load(fullfile(basedir, subfolder, clinicalmatfile), 'tmPatient', 'tmMicrobiology', 'tmClinicVisits', 'tmPFT', 'tmAdmissions', ...
        'tmAntibiotics', 'tmCRP', 'tmEndStudy');
    cdPatient      = tmPatient;
    cdMicrobiology = tmMicrobiology;
    cdClinicVisits = tmClinicVisits;
    cdPFT          = tmPFT;
    cdAdmissions   = tmAdmissions;
    cdAntibiotics  = tmAntibiotics;
    cdCRP          = tmCRP;
    cdEndStudy     = tmEndStudy;
    cdDrugTherapy  = [];
    cdOtherVisits  = [];
    cdHghtWght     = [];
    cdMedications  = [];
    cdNewMeds      = [];
    cdUnplannedContact = [];
elseif ismember(study, 'CL')
    load(fullfile(basedir, subfolder, clinicalmatfile), 'clPatient', 'clMicrobiology', 'clClinicVisits', 'clPFT', 'clAdmissions', ...
        'clAntibiotics', 'clCRP', 'clEndStudy', 'clOtherVisits', 'clHghtWght');
    cdPatient      = clPatient;
    cdMicrobiology = clMicrobiology;
    cdClinicVisits = clClinicVisits;
    cdPFT          = clPFT;
    cdAdmissions   = clAdmissions;
    cdAntibiotics  = clAntibiotics;
    cdCRP          = clCRP;
    cdEndStudy     = clEndStudy;
    cdOtherVisits  = clOtherVisits;
    cdHghtWght     = clHghtWght;
    cdDrugTherapy  = [];
    cdMedications  = [];
    cdNewMeds      = [];
    cdUnplannedContact = [];
elseif ismember(study, 'BR')
    load(fullfile(basedir, subfolder, clinicalmatfile), 'brPatient', 'brDrugTherapy', 'brMicrobiology', 'brClinicVisits', 'brPFT', 'brAdmissions', ...
        'brAntibiotics', 'brCRP', 'brEndStudy', 'brOtherVisits', 'brHghtWght', 'brUnplannedContact');
    cdPatient      = brPatient;
    cdDrugTherapy  = brDrugTherapy;
    cdMicrobiology = brMicrobiology;
    cdClinicVisits = brClinicVisits;
    cdPFT          = brPFT;
    cdAdmissions   = brAdmissions;
    cdAntibiotics  = brAntibiotics;
    cdCRP          = brCRP;
    cdEndStudy     = brEndStudy;
    cdOtherVisits  = brOtherVisits;
    cdHghtWght     = brHghtWght;
    cdMedications  = [];
    cdNewMeds      = [];
    cdUnplannedContact = brUnplannedContact;
end
toc
end