Description of plotProbDistribution
Home > Code > smartcare > plotProbDistribution.m
plotProbDistribution
PURPOSE
plotProbDistribution - plots a prob distribution
SYNOPSIS
function [xl, yl] = plotProbDistribution(ax, max_offset, pdoffset, xl, yl, marker, linewidth, markersize, markerec, markerfc)
DESCRIPTION
 plotProbDistribution - plots a prob distribution
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
am4PlotsAndSavePredictions am4PlotsAndSavePredictions - plots measures prior to
amEMMCAnimatedProbDistConcurrent amEMMCAnimatedProbDistConcurrent - function to display animated
amEMMCCompareModelRunToTestData amEMMCCompareModelRunToTestData - compares the output of a chosen model run to
amEMMCCompareModelRuns
amEMMCPlotsAndSavePredictions amEMMCPlotsAndSavePredictions - plots measures prior to
amEMPlotsAndSavePredictions amEMPlotsAndSavePredictions - plots measures prior to
animatedProbDistConcurrent animatedALingmentConcurrent - function to display animated curve
compareModelRunToTestData compareModelRunToTestData - compares the output of a chosen model run to
compareModelRuns
compareModelRunsScript
createLabelledInterventions createLabelledInterventions - plots measurement data and asks for lower
plotLabelledInterventions plotLabelledInterventions - plots all the labelled test data
SOURCE CODE
function [xl, yl] = plotProbDistribution(ax, max_offset, pdoffset, xl, yl, marker, linewidth, markersize, markerec, markerfc)
% plotProbDistribution - plots a prob distribution
line(ax, [0:max_offset-1], reshape(pdoffset, [max_offset,1]), ...
    'Color', markerec, ...
    'LineStyle', '-', ...
    'LineWidth', linewidth, ...
    'Marker', marker, ...
    'MarkerSize', markersize,...
    'MarkerEdgeColor', markerec,...
    'MarkerFaceColor', markerfc);
xl = [0 max(max_offset-1, xl(2))];
xlim(xl);
yl = [0 max(max(pdoffset) * 1.1, yl(2))];
ylim(yl);
end