Description of plotSuperimposedAlignedCurvesForPaper
Home > Code > smartcare > plotSuperimposedAlignedCurvesForPaper.m
plotSuperimposedAlignedCurvesForPaper
PURPOSE
plotSuperimposedAlignedCurves - plots the aligned curves for each of the
SYNOPSIS
function plotSuperimposedAlignedCurvesForPaper(ax, meancurvemean, xl, yl,tmpmeasures, tmpnmeasures, min_offset, max_offset, align_wind, ex_start, study)
DESCRIPTION
 plotSuperimposedAlignedCurves - plots the aligned curves for each of the
 measures superimposed on a single plot to show any timing differences in
 the declines
CROSS-REFERENCE INFORMATION
This function calls:
getColourForMeasure getColorForMeasure - returns the RGB value of the colour for a given
plotLatentCurve plotLatentCurve - plots the latent curve actual and smoothed
plotVerticalLine plotVerticalLine - plots a vertical line
sortMeasuresForPaper sortMeasuresForPaper - returns a sorted measures table in the order to
This function is called by:
amEMMCPlotSuperimposedAlignedCurvesForPaper3Recovery amEMMCPlotSuperimposedAlignedCurves3 - wrapper around the
amEMMCPlotSuperimposedAlignedCurvesForPaper amEMMCPlotSuperimposedAlignedCurves - wrapper around the
amEMMCPlotSuperimposedAlignedCurvesForPaper2 amEMMCPlotSuperimposedAlignedCurves2 - wrapper around the
amEMMCPlotSuperimposedAlignedCurvesForPaper3 amEMMCPlotSuperimposedAlignedCurves3 - wrapper around the
SOURCE CODE
function plotSuperimposedAlignedCurvesForPaper(ax, meancurvemean, xl, yl, ...
    tmpmeasures, tmpnmeasures, min_offset, max_offset, align_wind, ex_start, study)
% plotSuperimposedAlignedCurves - plots the aligned curves for each of the
% measures superimposed on a single plot to show any timing differences in
% the declines
anchor = 1; % latent curve is to be anchored on the plot (right side at min_offset)
[tmpmeasures] = sortMeasuresForPaper(study, tmpmeasures);
for m = 1:tmpnmeasures
    thiscolour = getColourForMeasure(tmpmeasures.DisplayName{m});
    lstyle = '-';
    lwidth = 1.5;
    [xl, yl] = plotLatentCurve(ax, max_offset, (align_wind + ex_start), (min_offset + ex_start), meancurvemean(:, tmpmeasures.Index(m)), xl, yl, thiscolour, lstyle, lwidth, anchor);
end
if ex_start ~= 0
    [xl, yl] = plotVerticalLine(ax, 0, xl, yl, 'black', '-', 0.5); % plot ex_start
end
end