Description of plotLatentCurve
Home > Code > smartcare > plotLatentCurve.m
plotLatentCurve
PURPOSE
plotLatentCurve - plots the latent curve actual and smoothed
SYNOPSIS
function [xl, yl] = plotLatentCurve(ax, max_offset, align_wind, offset, meancurve, xl, yl, colour, linestyle, linewidth, anchor)
DESCRIPTION
 plotLatentCurve - plots the latent curve actual and smoothed
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
am4PlotAndSaveAlignedCurves am4PlotAndSaveAlignedCurves - plots the curves pre and post alignment for
am4PlotsAndSavePredictions am4PlotsAndSavePredictions - plots measures prior to
am4VisualiseAlignmentDetail am4VisualiseAlignmentDetail - creates a plot of horizontal bars showing
amEMMCCompareModelRunToTestData amEMMCCompareModelRunToTestData - compares the output of a chosen model run to
amEMMCCompareModelRuns
amEMMCPlotsAndSavePredictions amEMMCPlotsAndSavePredictions - plots measures prior to
amEMPlotAlignedCurve amEMPlotAlignedCurve - plots a latent curve for a given measure (pre and post alignment)
amEMPlotAndSaveAlignedCurvesBasic amEMPlotAndSaveAlignedCurvesBasic - plots the curves pre and post alignment for
amEMPlotsAndSavePredictions amEMPlotsAndSavePredictions - plots measures prior to
amEMVisualiseAlignmentDetail amEMVisualiseAlignmentDetail - creates a plot of horizontal bars showing
compareModelRunToTestData compareModelRunToTestData - compares the output of a chosen model run to
compareModelRuns
compareModelRunsScript
plotSuperimposedAlignedCurves plotSuperimposedAlignedCurves - plots the aligned curves for each of the
plotSuperimposedAlignedCurvesForPaper plotSuperimposedAlignedCurves - plots the aligned curves for each of the
SOURCE CODE
function [xl, yl] = plotLatentCurve(ax, max_offset, align_wind, offset, meancurve, xl, yl, colour, linestyle, linewidth, anchor)
% plotLatentCurve - plots the latent curve actual and smoothed
if anchor == 1
    dfrom = max_offset + align_wind -1;
    dto = offset + 1;
else
    dfrom = max_offset + align_wind - 1 - offset;
    dto = 1;
end
line(ax, (-1 * dfrom):(-1 * dto), ...
    meancurve(1:max_offset + align_wind - 1 - offset), ...
    'Color', colour, ...
    'LineStyle', linestyle, ...
    'LineWidth', linewidth);
%line(ax, ((-1 * (max_offset + align_wind - 1)) + offset: -1), ...
%    (meancurve(1:max_offset + align_wind - 1 - offset)), ...
%    'Color', colour, ...
%    'LineStyle', linestyle, ...
%    'LineWidth', linewidth);
xl = [min(min((-1 * (max_offset + align_wind - 1))), xl(1)) max(max(-1), xl(2))];
xlim(xl);
yl = [min(min(meancurve(1:max_offset + align_wind - 1 - offset) * 0.99), yl(1)) max(max(meancurve(1:max_offset + align_wind - 1 - offset) * 1.01), yl(2))];
if yl(1)==yl(2)
    yl = [yl(1), yl(1)+0.01];
end
ylim(yl);
end