Description of plotExStart
Home > Code > smartcare > plotExStart.m
plotExStart
PURPOSE
plotExStart - plots the predicted exacerbation start plus average
SYNOPSIS
function [xl, yl] = plotExStart(ax, ex_start, offset, xl, yl, colour, linestyle, linewidth)
DESCRIPTION
 plotExStart - plots the predicted exacerbation start plus average
 ex_start
CROSS-REFERENCE INFORMATION
This function calls:
plotVerticalLine plotVerticalLine - plots a vertical line
This function is called by:
am4PlotsAndSavePredictions am4PlotsAndSavePredictions - plots measures prior to
amEMMCCompareModelRunToTestData amEMMCCompareModelRunToTestData - compares the output of a chosen model run to
amEMMCCompareModelRuns
amEMMCPlotSingleMeasureByLCSet amEMMCPlotSingleMeasureByLCSet - plots a given measure prior to
amEMMCPlotsAndSavePredictions amEMMCPlotsAndSavePredictions - plots measures prior to
amEMPlotsAndSavePredictions amEMPlotsAndSavePredictions - plots measures prior to
compareModelRunToTestData compareModelRunToTestData - compares the output of a chosen model run to
compareModelRuns
compareModelRunsScript
SOURCE CODE
function [xl, yl] = plotExStart(ax, ex_start, offset, xl, yl, colour, linestyle, linewidth)
% plotExStart - plots the predicted exacerbation start plus average
% ex_start
% plot vertical line for predicted exacerbation start
[xl, yl] = plotVerticalLine(ax, ex_start + offset, xl, yl, colour, linestyle, linewidth);
% plot short vertical line for average exacerbation start indicator
tempyl = yl;
tempyl(2) = yl(1) + ((yl(2)-yl(1)) * 0.1);
plotVerticalLine(ax, ex_start, xl, tempyl, 'black', linestyle, linewidth);
end