Description of runAlignmentModelEMFcnFEV1Split
Home > Code > smartcare > runAlignmentModelEMFcnFEV1Split.m
runAlignmentModelEMFcnFEV1Split
PURPOSE
function to run the alignment model (EM version) given a set of run
SYNOPSIS
function runAlignmentModelEMFcnFEV1Split(amRunParameters)
DESCRIPTION
 function to run the alignment model (EM version) given a set of run
 parameters
CROSS-REFERENCE INFORMATION
This function calls:
amEMAlignCurves amEMAlignCurves - function to align measurement curves prior to intervention
amEMPlotAndSaveAlignedCurves amEMPlotAndSaveAlignedCurves - plots the curves pre and post alignment for
amEMPlotsAndSavePredictions amEMPlotsAndSavePredictions - plots measures prior to
amEMPreprocessInterventions amEMPreprocessInterventions - preprocess intervention data and associated
amEMPreprocessMeasures amEMPreprocessMeasures - various bits of pre-processing to measures table
amEMSetModelRunParametersFromTable amEMSetModelRunParameters - sets the various run parameters for the model
amEMVisualiseAlignmentDetail amEMVisualiseAlignmentDetail - creates a plot of horizontal bars showing
calcConfidenceBounds calcConfidenceBounds - calculates the lower and upper confidence bounds
calcImputedProbabilities getImputedProbabilities - gets the probabilities for the set of held back
calcTotalOutliers calcTotalOutliers - sums up the total outliers after alignment
calculateMuNormalisation calculateMuNormalisation - - populates an array of ninterventions by
calculateSigmaNormalisation calculateSigmaNormalisation - populates an array of ninterventions by
createHeldBackcube createHeldBackcube - creates an index array indicating points to be held
createIntrDatacube createIntrDatacube - creates the data cube for offset + alignement window
createNormalisedIntrDatacube createNormalisedIntrDatacube - creates the normalised data cube by
setBaseDir setBaseDir - sets the root directory for the code, plots, data files etc
This function is called by:
runAlignmentModelEMScriptFEV1Split
SOURCE CODE
function runAlignmentModelEMFcnFEV1Split(amRunParameters)
% function to run the alignment model (EM version) given a set of run
% parameters
% set the various model run parameters
[mversion, study, modelinputsmatfile, datademographicsfile, dataoutliersfile, ...
    sigmamethod, mumethod, curveaveragingmethod, smoothingmethod, offsetblockingmethod, ...
    measuresmask, runmode, modelrun, imputationmode, confidencemode, printpredictions, ...
    max_offset, align_wind, ex_start, outprior, heldbackpct, confidencethreshold] ...
    = amEMSetModelRunParametersFromTable(amRunParameters);
fprintf('Running Alignment Model %s\n', mversion);
fprintf('\n');
% load the required input data
tic
basedir = setBaseDir();
subfolder = 'MatlabSavedVariables';
fnmodelrun = fullfile(basedir, subfolder, sprintf('%s.mat',modelrun));
fprintf('Loading alignment model Inputs data\n');
load(fullfile(basedir, subfolder, modelinputsmatfile));
fprintf('Loading datademographics by patient\n');
load(fullfile(basedir, subfolder, datademographicsfile));
fprintf('Loading data outliers\n');
load(fullfile(basedir, subfolder, dataoutliersfile));
fprintf('Loading Predictive Model Patient Measures Stats\n');
load(fullfile(basedir, subfolder, 'SCpredictivemodelinputs.mat'), 'pmPatientMeasStats');
toc
fprintf('Creating Upper and Lower 50%% splits for FEV1\n');
ntiles = 2;
npmpatients = size(unique(pmPatientMeasStats.PatientNbr),1);
mfev1idx  = measures.Index(ismember(measures.DisplayName, 'LungFunction'));
fev1max  = pmPatientMeasStats(pmPatientMeasStats.MeasureIndex == mfev1idx, {'PatientNbr', 'Study', 'ID', 'RobustMax'});
fev1max.Properties.VariableNames({'RobustMax'}) = {'Max'};
fev1max = sortrows(fev1max, {'Max'}, 'ascend');
fev1max.NTile(:) = 0;
for i = 1:npmpatients
    fev1max.NTile(i) = ceil((i * ntiles)/ npmpatients);
end
fev1max = sortrows(fev1max, {'Study', 'ID'}, 'ascend');
amInterventionsKeep = amInterventions;
ninterventionsKeep = ninterventions;
for t = 1:ntiles
    fprintf('Running for FEV1 split %d\n', t);
    amInterventions = amInterventionsKeep(ismember(amInterventionsKeep.SmartCareID, fev1max.ID(fev1max.NTile == t)),:);
    ninterventions = size(amInterventions,1);
    tic
    fprintf('Preparing input data\n');
    sversion = sprintf('FEV1Split%d', t);
    baseplotname = sprintf('%s%s_sig%d_mu%d_ca%d_sm%d_rm%d_ob%d_im%d_cm%d_mm%d_mo%d_dw%d', study, mversion, sigmamethod, mumethod, curveaveragingmethod, ...
        smoothingmethod, runmode, offsetblockingmethod, imputationmode, confidencemode, measuresmask, max_offset, align_wind);
    detaillog = true;
    % pre-process measures table and associated measurement data
    [amDatacube, measures, nmeasures] = amEMPreprocessMeasures(amDatacube, amInterventions, measures, ...
        demographicstable, measuresmask, align_wind, npatients, ndays, ninterventions);
    % create cube for data window data by intervention (for each measure)
    [amIntrDatacube] = createIntrDatacube(amDatacube, amInterventions, align_wind, ...
        max_offset, ninterventions, nmeasures, curveaveragingmethod);
    % pre-process intervention table and associated measurement data
    [amInterventions, amIntrDatacube, ninterventions] = amEMPreprocessInterventions(amInterventions, ...
        amIntrDatacube, max_offset, align_wind, ninterventions, nmeasures);
    % populate multiplicative normalisation (sigma) values based on methodology
    % selected
    normstd = calculateSigmaNormalisation(amInterventions, measures, demographicstable, ninterventions, nmeasures, sigmamethod);
    % calculate additive normalisation (mu) based on methodology
    % and then create normalised data cube.
    normmean = calculateMuNormalisation(amDatacube, amInterventions, measures, demographicstable, ...
        dataoutliers, align_wind, ninterventions, nmeasures, mumethod);
    % populate normalised data cube by intervention
    [amIntrNormcube] = createNormalisedIntrDatacube(amIntrDatacube, normmean, normstd, ...
        max_offset, align_wind, ninterventions, nmeasures, sigmamethod);
    % populate index array for held back points (to be used for imputation
    [amHeldBackcube] = createHeldBackcube(amIntrDatacube, max_offset, align_wind, ninterventions, nmeasures, heldbackpct, imputationmode);
    toc
    fprintf('\n');
    tic
    fprintf('Running alignment\n');
    % should really move this into AlignCurves function or override with value
    % loaded in there
    for i=1:size(amInterventions,1)
        amInterventions.Offset(i) = 0;
    end
    initial_offsets = amInterventions.Offset;
    if runmode == 6
        run_type = 'Pre-selected Start';
    else
        run_type = 'Uniform Start';
    end
    [meancurvesumsq, meancurvesum, meancurvecount, meancurvemean, meancurvestd, animatedmeancurvemean, profile_pre, ...
        offsets, animatedoffsets, hstg, pdoffset, overall_hist, overall_pdoffset, animated_overall_pdoffset, ...
        isOutlier, ppts, qual, min_offset, niterations] = amEMAlignCurves(amIntrNormcube, amHeldBackcube, amInterventions, outprior, measures, ...
        normstd, max_offset, align_wind, nmeasures, ninterventions, detaillog, sigmamethod, smoothingmethod, offsetblockingmethod, runmode, fnmodelrun);
    fprintf('%s - ErrFcn = %.8f\n', run_type, qual);
    % save the zero offset pre-profile to unaligned_profile so all plots show a
    % consistent unaligned curve as the pre-profile.
    unaligned_profile = profile_pre;
    plotname = sprintf('%s_obj%.8f', baseplotname, qual);
    % plot and save aligned curves (pre and post)
    amEMPlotAndSaveAlignedCurves(unaligned_profile, meancurvemean, meancurvecount, meancurvestd, offsets, ...
        measures, 0, min_offset, max_offset, align_wind, nmeasures, run_type, 0, sigmamethod, plotname, 'Plots');
    toc
    fprintf('\n');
    if ex_start == 0
        ex_start = input('Look at best start and enter exacerbation start: ');
        fprintf('\n');
    end
    tic
    run_type = 'Best Alignment';
    plotname = sprintf('%s_ex%d_obj%.8f', baseplotname, ex_start, qual);
    plotsubfolder = strcat('Plots', '/', plotname);
    mkdir(strcat(basedir, plotsubfolder));
    [amInterventions] = calcConfidenceBounds(overall_pdoffset, amInterventions, offsets, min_offset, max_offset, ninterventions, confidencethreshold, confidencemode);
    [sorted_interventions, max_points] = amEMVisualiseAlignmentDetail(amIntrNormcube, amHeldBackcube, amInterventions, meancurvemean, ...
        meancurvecount, meancurvestd, overall_pdoffset, measures, min_offset, max_offset, align_wind, nmeasures, ninterventions, ...
        run_type, ex_start, curveaveragingmethod, plotname, plotsubfolder);
    amEMPlotAndSaveAlignedCurves(unaligned_profile, meancurvemean, meancurvecount, meancurvestd, offsets, ...
        measures, max_points, min_offset, max_offset, align_wind, nmeasures, run_type, ex_start, sigmamethod, plotname, plotsubfolder);
    % calculate the total number of outliers and the total number of data
    % points
    [totaloutliers, totalpoints] = calcTotalOutliers(amIntrDatacube, isOutlier, amHeldBackcube, offsets, max_offset, align_wind, ninterventions);
    % calculate imputed probabilities for held back points
    [amImputedCube, imputedscore] = calcImputedProbabilities(amIntrNormcube, amHeldBackcube, ...
        meancurvemean, meancurvestd, normstd, overall_pdoffset, max_offset, align_wind, ...
        nmeasures, ninterventions,sigmamethod, smoothingmethod, imputationmode);
    toc
    fprintf('\n');
    tic
    basedir = setBaseDir();
    subfolder = 'MatlabSavedVariables';
    outputfilename = sprintf('%s.mat', plotname);
    fprintf('Saving alignment model results to file %s\n', outputfilename);
    fprintf('\n');
    save(fullfile(basedir, subfolder, outputfilename), 'amDatacube', 'amIntrDatacube', 'amIntrNormcube', ...
        'amHeldBackcube', 'amImputedCube', 'imputedscore', 'amInterventions', ...
        'meancurvesumsq', 'meancurvesum', 'meancurvecount', 'meancurvemean', 'meancurvestd', 'animatedmeancurvemean', ...
        'initial_offsets', 'offsets', 'animatedoffsets', 'qual', 'unaligned_profile', ...
        'hstg', 'pdoffset', 'overall_hist', 'overall_pdoffset', 'animated_overall_pdoffset', ...
        'ppts', 'isOutlier', 'outprior', 'totaloutliers', 'totalpoints', ...
        'sorted_interventions', 'normmean', 'normstd', 'measures', 'baseplotname', 'plotname', 'plotsubfolder', ...
        'study', 'mversion', 'min_offset', 'max_offset', 'align_wind', 'ex_start', 'confidencethreshold', ...
        'sigmamethod', 'mumethod', 'curveaveragingmethod', 'smoothingmethod', 'offsetblockingmethod', ...
        'measuresmask', 'runmode', 'imputationmode', 'confidencemode', 'printpredictions', ...
        'nmeasures', 'ninterventions', 'niterations');
    toc
    fprintf('\n');
    if printpredictions == 1
        tic
        fprintf('Plotting prediction results\n');
        for i=1:ninterventions
            amEMPlotsAndSavePredictions(amInterventions, amIntrDatacube, measures, pdoffset, ...
                overall_pdoffset, hstg, overall_hist, meancurvemean, normmean, normstd, isOutlier, ex_start, ...
                i, nmeasures, max_offset, align_wind, sigmamethod, plotname, plotsubfolder);
        end
        toc
        fprintf('\n');
    end
end
end