Description of savePlotInDirAsSVG
Home > Code > smartcare > savePlotInDirAsSVG.m
savePlotInDirAsSVG
PURPOSE
savePlots - saves the figure to png and svp file types in the specified
SYNOPSIS
function savePlotInDirAsSVG(f, name, subfolder)
DESCRIPTION
 savePlots - saves the figure to png and svp file types in the specified
 subfolder
CROSS-REFERENCE INFORMATION
This function calls:
setBaseDir setBaseDir - sets the root directory for the code, plots, data files etc
This function is called by:
amEMMCPlotSuperimposedAlignedCurvesForPaper3Recovery amEMMCPlotSuperimposedAlignedCurves3 - wrapper around the
amEMMCPlotVariablesVsLatentCurveSetForPaperRecovery amEMMCPlotVariablesVsLatentCurveSet - compact plots of various variables
amEMMCPlotHistOfTimeSinceLastExacerbation amEMMCPlotHistogramTimeSinceLastExacerbation - function to plot
amEMMCPlotHistogramOfTimeToTreatForPaper amEMMCPlotHistogramOfTimeToTreatForPaper - plots a historgram of the time
amEMMCPlotInterventionsByLatentCurveSetForPaper amEMMCPlotInterventionsByLatentCurveSetForPaper - plots interventions and
amEMMCPlotSuperimposedAlignedCurves amEMMCPlotSuperimposedAlignedCurves - wrapper around the
amEMMCPlotSuperimposedAlignedCurvesForPaper amEMMCPlotSuperimposedAlignedCurves - wrapper around the
amEMMCPlotSuperimposedAlignedCurvesForPaper2 amEMMCPlotSuperimposedAlignedCurves2 - wrapper around the
amEMMCPlotSuperimposedAlignedCurvesForPaper3 amEMMCPlotSuperimposedAlignedCurves3 - wrapper around the
amEMMCPlotSuperimposedMeasuresB4Intr amEMMCPlotSuperimposedAlignedCurves - wrapper around the
amEMMCPlotVariablesVsLatentCurveSetForPaper amEMMCPlotVariablesVsLatentCurveSet - compact plots of various variables
calcExFrequencyByDT calcExFrequencyByDT - function to analyse the frequency of exacerbations
createMeasuresHeatmapSorted createMeasuresHeatmapSorted - creates the Patient/Measures
createMeasuresHeatmapSortedForPaper createMeasuresHeatmapSortedForPaper - creates the Patient/Measures
plotLCSetByHospital plotLCSetByHospital - plots barcharts of Latent Curve set by hospital
plotNbrIntrByPatient plotNbrIntrByPatient - plots bar chart of number of interventions by
visualiseExacerbationForPaperFcn visualiseExacerbationForPaperFcn - plots measures around an exacerbation
visualiseExacerbationForPaperFcn2 visualiseExacerbationForPaperFcn - plots measures around an exacerbation
visualiseExacerbationForPaperFcn3 visualiseExacerbationForPaperFcn3 - plots measures around an exacerbation
visualiseMeasures
visualiseMeasuresFcn visualiseMeasuresFcn - plots clinical and home measures
visualiseMeasuresForPaperFcn visualiseMeasuresForPaperFcn - plots clinical and home measures
visualiseMeasuresForPaperFcn2 visualiseMeasuresForPaperFcn2 - plots clinical and home measures
SOURCE CODE
function savePlotInDirAsSVG(f, name, subfolder)
% savePlots - saves the figure to png and svp file types in the specified
% subfolder
% save plot
basedir = setBaseDir();
filename = [name '.svg'];
saveas(f,fullfile(basedir, subfolder, filename));
end