Description of scaleDaysByPatient
Home > Code > smartcare > scaleDaysByPatient.m
scaleDaysByPatient
PURPOSE
scaleDateByPatient - adds a new column to physdata for the scaled datenum
SYNOPSIS
function [physdata] = scaleDaysByPatient(physdata,doupdates)
DESCRIPTION
 scaleDateByPatient - adds a new column to physdata for the scaled datenum
 (relative to the first measurement date for each patient)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
analyseAndHandleDateOutliers analyseAndHandleDateOutliers - function to do the following :-
loadbreathedata 1st Breathe data processing step and analysis from raw measurements
loadbreathemeasurementdata 1st Breathe data processing step and analysis from raw measurements
loadclimbdata
loadsmartcaredata
SOURCE CODE
function [physdata] = scaleDaysByPatient(physdata,doupdates)
% scaleDateByPatient - adds a new column to physdata for the scaled datenum
% (relative to the first measurement date for each patient)
tic
fprintf('Scaling the date relative to the first measurement date for each patient\n');
fprintf('------------------------------------------------------------------------\n');
physdata = sortrows(physdata, {'SmartCareID', 'DateNum', 'RecordingType'}, 'ascend');
% get min and max measurement dates for each SmartCare ID
minDatesByPatient = varfun(@min, physdata(:,{'SmartCareID', 'DateNum'}), 'GroupingVariables', 'SmartCareID');
minDatesByPatient.GroupCount = [];
minDatesByPatient.Properties.VariableNames(2) = {'MinPatientDateNum'};
if doupdates
    physdata = innerjoin(physdata, minDatesByPatient);
    physdata.ScaledDateNum = physdata.DateNum - physdata.MinPatientDateNum +1;
    physdata.MinPatientDateNum = [];
    fprintf('Updates completed\n');
end
toc
fprintf('\n');
end