Description of selectValFromRange
Home > Code > smartcare > selectValFromRange.m
selectValFromRange
PURPOSE
selectValFromRange - allows you to select a value from a range
SYNOPSIS
function [value] = selectValFromRange(questext, fromrange, torange)
DESCRIPTION
 selectValFromRange - allows you to select a value from a range
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
amEMMCCreateLabelledInterventions amEMMCCreateLabelledInterventions - plots measurement data and asks for lower
runModelUtilityFunctionsEMMC
selectLabBound selectLabBound - wrapper around range selection function for labelled
SOURCE CODE
function [value] = selectValFromRange(questext, fromrange, torange)
% selectValFromRange - allows you to select a value from a range
valid = false;
while ~valid
    svalue = input(sprintf('%s (%d:%d) ? ', questext, fromrange, torange), 's');
    value = str2double(svalue);
    if (isnan(value) || value < fromrange || value > torange)
        fprintf('Invalid choice\n');
        valid = false;
    else
        valid = true;
    end
end
end