Description of selectTreatmentGap
Home > Code > smartcare > selectTreatmentGap.m
selectTreatmentGap
PURPOSE
selectTreatmentGap - enter the gap between the end of a treatment and the
SYNOPSIS
function treatgap = selectTreatmentGap()
DESCRIPTION
 selectTreatmentGap - enter the gap between the end of a treatment and the
 start of the next. Used to define the list of interventions
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
checkBreatheTreatmentsVsSelectMeasuresPost creates list of oral & IV treatments for recovery study
createAlignmentModelInputsRecovery creates the inputs for the model
findDataAnomaliesRecovery highlight data anomalies to be optionnaly excluded prior to run the alignment model
JosieQuery
amEMMCSelectModelRunFromDir amEMMCSelectModelRunFromDir- allows you to load the saved variables from a
calcClinicalInfoForPaper
checkBreatheTreatmentsVsSelectMeasuresPrior creates list of oral & IV treatments
checkIVTreatmentsVsMeasuresPriorNew creates list of oral & IV treatments
createAlignmentModelInputs creates the inputs for the model
findDataAnomalies highlight data anomalies to be optionnaly excluded prior to run the alignment model
runModelUtilityFunctionsEMMC
runPlotsForPaperEMMC
visualiseExacerbationTimeline
SOURCE CODE
function treatgap = selectTreatmentGap()
% selectTreatmentGap - enter the gap between the end of a treatment and the
% start of the next. Used to define the list of interventions
streatgap = input('Enter gap in treatments (days) ? ', 's');
treatgap = str2double(streatgap);
if (isnan(treatgap) || treatgap < 1 || treatgap > 50)
    fprintf('Invalid choice - defaulting to 10\n');
    treatgap = 10;
end
end