Description of selectStudy
Home > Code > smartcare > selectStudy.m
selectStudy
PURPOSE
selectStudy - choose which study to run for
SYNOPSIS
function [studynbr, study, studyfullname] = selectStudy()
DESCRIPTION
 selectStudy - choose which study to run for
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
plotPatientProfiles plot a profile of each measures for each patient over the whole enrolment period
checkBreatheTreatmentsVsSelectMeasuresPost creates list of oral & IV treatments for recovery study
findDataAnomaliesRecovery highlight data anomalies to be optionnaly excluded prior to run the alignment model
EmemLungFunctionComparison
JosieQuery
calcClinicalInfoForPaper
checkBreatheTreatmentsVsSelectMeasuresPrior creates list of oral & IV treatments
checkClinicalVsHomeWeightMeasures
checkDatesAdmissionsVsAntibiotics
checkDatesClinicVisitsVsCRPNew
checkDatesClinicVisitsVsPFTNew
checkDatesIVTreatmentsVsMeasurementDate
checkDatesIVTreatmentsVsPatientStudyDate
checkIVTreatmentsVsMeasuresPriorNew creates list of oral & IV treatments
checkStudyDateVsFirstMeasurementDate
createAlignmentModelInputs creates the inputs for the model
createClinMeasPredExcelDataByPatient
extractClinicalAndHomeFEV1Measures
findDataAnomalies highlight data anomalies to be optionnaly excluded prior to run the alignment model
plotAlignedCurveComparison
runModelUtilityFunctionsEMMC
runPlotsForPaperEMMC
visualiseExacerbationTimeline
visualiseMeasures
visualisePatientSummary
SOURCE CODE
function [studynbr, study, studyfullname] = selectStudy()
% selectStudy - choose which study to run for
nstudies = 4;
sstudynbr = input('Enter Study to run for (1 = SmartCare, 2 = TeleMed, 3 = Climb, 4 = Breathe): ', 's');
studynbr = str2double(sstudynbr);
if (isnan(studynbr) || studynbr < 1 || studynbr > nstudies)
    fprintf('Invalid choice\n');
    studynbr = -1;
    study = '**';
    return;
end
if studynbr == 1
    study = 'SC';
    studyfullname = 'SmartCare';
elseif studynbr == 2
    study = 'TM';
    studyfullname = 'TeleMed';
elseif studynbr == 3
    study = 'CL';
    studyfullname = 'Climb';
elseif studynbr == 4
    study = 'BR';
    studyfullname = 'Breathe';
end
end