Description of setTicks
Home > Code > smartcare > setTicks.m
setTicks
PURPOSE
setTicks - create an array of ticks for a plot axis
SYNOPSIS
function [ticks] = setTicks(minval, maxval, nticks)
DESCRIPTION
 setTicks - create an array of ticks for a plot axis
CROSS-REFERENCE INFORMATION
This function calls:
roundRangeScaled roundScaled - scale a number appropriate to its magnitude
This function is called by:
visualiseExacerbationForPaperFcn visualiseExacerbationForPaperFcn - plots measures around an exacerbation
visualiseExacerbationForPaperFcn2 visualiseExacerbationForPaperFcn - plots measures around an exacerbation
visualiseExacerbationForPaperFcn3 visualiseExacerbationForPaperFcn3 - plots measures around an exacerbation
visualiseMeasuresFcn visualiseMeasuresFcn - plots clinical and home measures
visualiseMeasuresForPaperFcn visualiseMeasuresForPaperFcn - plots clinical and home measures
visualiseMeasuresForPaperFcn2 visualiseMeasuresForPaperFcn2 - plots clinical and home measures
SOURCE CODE
function [ticks] = setTicks(minval, maxval, nticks)
% setTicks - create an array of ticks for a plot axis
ticks = zeros(nticks, 1);
%ticks(1) = ceil(minval/factor) * factor;
%ticks(nticks) = floor(maxval/factor) * factor;
roundedrange = roundRangeScaled(minval, maxval, 'inner');
ticks(1)      = roundedrange(1);
ticks(nticks) = roundedrange(2);
interval = (ticks(nticks) - ticks(1)) / (nticks - 1);
for i = 2:nticks - 1
    ticks(i) = round(ticks(1) + (i - 1) * interval);
end
end