Description of sortMeasuresForPaper
Home > Code > smartcare > sortMeasuresForPaper.m
sortMeasuresForPaper
PURPOSE
sortMeasuresForPaper - returns a sorted measures table in the order to
SYNOPSIS
function [measures] = sortMeasuresForPaper(study, measures)
DESCRIPTION
 sortMeasuresForPaper - returns a sorted measures table in the order to
 display measures in paper
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
amEMMCPlotSuperimposedAlignedCurvesForPaper3Recovery amEMMCPlotSuperimposedAlignedCurves3 - wrapper around the
amEMMCPlotSuperimposedAlignedCurvesForPaper amEMMCPlotSuperimposedAlignedCurves - wrapper around the
amEMMCPlotSuperimposedAlignedCurvesForPaper2 amEMMCPlotSuperimposedAlignedCurves2 - wrapper around the
amEMMCPlotSuperimposedAlignedCurvesForPaper3 amEMMCPlotSuperimposedAlignedCurves3 - wrapper around the
plotSuperimposedAlignedCurvesForPaper plotSuperimposedAlignedCurves - plots the aligned curves for each of the
plotSuperimposedMeasuresB4IntrForPaper plotSuperimposedMeasuresB4Intr - plots the measures for the period prior
testLayoutScript
visualiseMeasuresForPaperFcn2 visualiseMeasuresForPaperFcn2 - plots clinical and home measures
SOURCE CODE
function [measures] = sortMeasuresForPaper(study, measures)
% sortMeasuresForPaper - returns a sorted measures table in the order to
% display measures in paper
if ismember(study, {'SC'})
    measures = measures([find(ismember(measures.DisplayName,'LungFunction')),     ...
                         find(ismember(measures.DisplayName,'O2Saturation')),     ...
                         find(ismember(measures.DisplayName,'PulseRate')),        ...
                         find(ismember(measures.DisplayName,'Activity')),         ...
                         find(ismember(measures.DisplayName,'Weight')),           ...
                         find(ismember(measures.DisplayName,'Temperature')),      ...
                         find(ismember(measures.DisplayName,'Cough')),            ...
                         find(ismember(measures.DisplayName,'Wellness')),         ...
                         find(ismember(measures.DisplayName,'SleepActivity'))     ], :);
elseif ismember(study, {'CL'})
    measures = measures([find(ismember(measures.DisplayName,'FEV1')),             ...
                         find(ismember(measures.DisplayName,'InterpFEV1')),       ...
                         find(ismember(measures.DisplayName,'O2Saturation')),     ...
                         find(ismember(measures.DisplayName,'PulseRate')),        ...
                         find(ismember(measures.DisplayName,'Temperature')),      ...
                         find(ismember(measures.DisplayName,'Weight')),           ...
                         find(ismember(measures.DisplayName,'InterpWeight')),     ...
                         find(ismember(measures.DisplayName,'Activity')),         ...
                         find(ismember(measures.DisplayName,'Cough')),            ...
                         find(ismember(measures.DisplayName,'Wellness')),         ...
                         find(ismember(measures.DisplayName,'Appetite')),         ...
                         find(ismember(measures.DisplayName,'Breathlessness')),   ...
                         find(ismember(measures.DisplayName,'RespiratoryRate')),  ...
                         find(ismember(measures.DisplayName,'SleepActivity')),    ...
                         find(ismember(measures.DisplayName,'SleepDisturbance')), ...
                         find(ismember(measures.DisplayName,'SputumVolume')),     ...
                         find(ismember(measures.DisplayName,'Tiredness'))         ], :);
elseif ismember(study, {'BR'})
    measures = measures([find(ismember(measures.DisplayName,'FEV1')),             ...
                         find(ismember(measures.DisplayName,'FEF2575')),          ...
                         find(ismember(measures.DisplayName,'FEV075')),           ...
                         find(ismember(measures.DisplayName,'FEV1DivFEV6')),      ...
                         find(ismember(measures.DisplayName,'FEV6')),             ...
                         find(ismember(measures.DisplayName,'LungFunction')),     ...
                         find(ismember(measures.DisplayName,'MinsAsleep')),       ...
                         find(ismember(measures.DisplayName,'MinsAwake')),        ...
                         find(ismember(measures.DisplayName,'O2Saturation')),     ...
                         find(ismember(measures.DisplayName,'PulseRate')),        ...
                         find(ismember(measures.DisplayName,'RestingHR')),        ...
                         find(ismember(measures.DisplayName,'Temperature')),      ...
                         find(ismember(measures.DisplayName,'Weight')),           ...
                         find(ismember(measures.DisplayName,'Calorie')),          ...
                         find(ismember(measures.DisplayName,'Cough')),            ...
                         find(ismember(measures.DisplayName,'Wellness')),         ...
                         find(ismember(measures.DisplayName,'HasColdOrFlu')),     ...
                         find(ismember(measures.DisplayName,'HasHayFever'))       ], :);
else
    fprintf('**** need to set sort order for study %s ****\n', study);
end
end