Description of xb25mean
Home > Code > smartcare > xb25mean.m
xb25mean
PURPOSE
xb25mean - returns the mean of the data points excluding the bottom 25% in x (sorted by
SYNOPSIS
function y = xb25mean(x)
DESCRIPTION
 xb25mean - returns the mean of the data points excluding the bottom 25% in x (sorted by
 magnitude)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
generateDataDemographicsByPatientFn generateDataDemographicsByPatientFn - function that creates data
visualiseExacerbationForPaperFcn visualiseExacerbationForPaperFcn - plots measures around an exacerbation
visualiseExacerbationForPaperFcn2 visualiseExacerbationForPaperFcn - plots measures around an exacerbation
visualiseExacerbationForPaperFcn3 visualiseExacerbationForPaperFcn3 - plots measures around an exacerbation
visualiseMeasuresForPaperFcn visualiseMeasuresForPaperFcn - plots clinical and home measures
visualiseMeasuresForPaperFcn2 visualiseMeasuresForPaperFcn2 - plots clinical and home measures
SOURCE CODE
function y = xb25mean(x)
% xb25mean - returns the mean of the data points excluding the bottom 25% in x (sorted by
% magnitude)
x = sort(x, 'ascend');
if size(x, 1) == 1
    dim = 2;
elseif size(x, 2) == 1
    dim = 1;
else
    fprintf('**** function only works for vectors ****');
    return
end
percentile25 = round(size(x, dim) * .25) + 1;
y = mean(x(percentile25:end));
end