Description of xu25std
Home > Code > smartcare > xu25std.m
xu25std
PURPOSE
xu25std - returns the std of the data points excluding the upper 25% in x (sorted by
SYNOPSIS
function y = xu25std(x)
DESCRIPTION
 xu25std - returns the std of the data points excluding the upper 25% in x (sorted by
 magnitude)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
generateDataDemographicsByPatientFn generateDataDemographicsByPatientFn - function that creates data
visualiseExacerbationForPaperFcn visualiseExacerbationForPaperFcn - plots measures around an exacerbation
visualiseExacerbationForPaperFcn2 visualiseExacerbationForPaperFcn - plots measures around an exacerbation
visualiseExacerbationForPaperFcn3 visualiseExacerbationForPaperFcn3 - plots measures around an exacerbation
visualiseMeasuresForPaperFcn visualiseMeasuresForPaperFcn - plots clinical and home measures
visualiseMeasuresForPaperFcn2 visualiseMeasuresForPaperFcn2 - plots clinical and home measures
SOURCE CODE
function y = xu25std(x)
% xu25std - returns the std of the data points excluding the upper 25% in x (sorted by
% magnitude)
x = sort(x, 'ascend');
if size(x, 1) == 1
    dim = 2;
elseif size(x, 2) == 1
    dim = 1;
else
    fprintf('**** function only works for vectors ****');
    return
end
percentile75 = round(size(x, dim) * .75);
y = std(x(1:percentile75));
end