Description of amEMMCPlotAndSaveAlignedCurvesRecovery
Home > Code > pdm > recovery > updatedModel > amEMMCPlotAndSaveAlignedCurvesRecovery.m
amEMMCPlotAndSaveAlignedCurvesRecovery
PURPOSE
amEMMCPlotAndSaveAlignedCurves - wrapper around the
SYNOPSIS
function amEMMCPlotAndSaveAlignedCurvesRecovery(profile_pre, meancurvemean, meancurvecount, meancurvestd, offsets, latentcurves,measures, max_points, offset, align_wind, nmeasures, run_type, ex_start, sigmamethod, plotname, plotsubfolder, nlatentcurves)
DESCRIPTION
 amEMMCPlotAndSaveAlignedCurves - wrapper around the
 amEMPlotAndSaveAlignedCurves to plot for each set of latent curves
CROSS-REFERENCE INFORMATION
This function calls:
amEMPlotAndSaveAlignedCurvesRecovery amEMPlotAndSaveAlignedCurves - plots the curves pre and post alignment for
This function is called by:
runAlignmentModelEMMCRecoveryFcn runs the alignment model (EM version) given a set of run parameters.
runFastAlignmentModelEMMCRecoveryFcn fast version with 1 plot (typical profile) + alignment result matfile
SOURCE CODE
function amEMMCPlotAndSaveAlignedCurvesRecovery(profile_pre, meancurvemean, meancurvecount, meancurvestd, offsets, latentcurves, ...
    measures, max_points, offset, align_wind, nmeasures, run_type, ex_start, sigmamethod, plotname, plotsubfolder, nlatentcurves)
% amEMMCPlotAndSaveAlignedCurves - wrapper around the
% amEMPlotAndSaveAlignedCurves to plot for each set of latent curves
for n = 1:nlatentcurves
    tmp_profile_pre    = reshape(profile_pre(n, :, :),    [align_wind + offset.span - 1, nmeasures]);
    tmp_meancurvemean  = reshape(meancurvemean(n, :, :),  [align_wind + offset.span - 1, nmeasures]);
    tmp_meancurvecount = reshape(meancurvecount(n, :, :), [align_wind + offset.span - 1, nmeasures]);
    tmp_meancurvestd   = reshape(meancurvestd(n, :, :),   [align_wind + offset.span - 1, nmeasures]);
    tmp_offsets        = offsets(latentcurves == n);
    tmp_plotname = sprintf('%s C%d', plotname, n);
    amEMPlotAndSaveAlignedCurvesRecovery(tmp_profile_pre, tmp_meancurvemean, tmp_meancurvecount, tmp_meancurvestd, ...
            tmp_offsets, measures, max_points(n, :), offset, align_wind, nmeasures, run_type, ex_start(n), sigmamethod, tmp_plotname, plotsubfolder);
end
end