Description of amEMMCPreprocessMeasuresRecovery
Home > Code > pdm > recovery > updatedModel > amEMMCPreprocessMeasuresRecovery.m
amEMMCPreprocessMeasuresRecovery
PURPOSE
amEMMCPreprocessMeasures - 1) select a set of measures, 2) filter
SYNOPSIS
function [amDatacube, measures, nmeasures] = amEMMCPreprocessMeasuresRecovery(amDatacube, amInterventions, measures,demographicstable, measuresmask, align_wind, npatients, ndays, ninterventions, nmeasures, study)
DESCRIPTION
 amEMMCPreprocessMeasures - 1) select a set of measures, 2) filter
 corresponding data and 3) compute high level statistics (for each measure)
CROSS-REFERENCE INFORMATION
This function calls:
getMeasureOverallMinMax getMeasureMinMax - returns the min and max value for a measure across all
getMeasuresMask reset measures mask
This function is called by:
createIntrNormDataCube create the array with the normalised data for each intervention
runAlignmentModelEMMCRecoveryFcn runs the alignment model (EM version) given a set of run parameters.
runFastAlignmentModelEMMCRecoveryFcn fast version with 1 plot (typical profile) + alignment result matfile
SOURCE CODE
function [amDatacube, measures, nmeasures] = amEMMCPreprocessMeasuresRecovery(amDatacube, amInterventions, measures, ...
    demographicstable, measuresmask, align_wind, npatients, ndays, ninterventions, nmeasures, study)
% amEMMCPreprocessMeasures - 1) select a set of measures, 2) filter
% corresponding data and 3) compute high level statistics (for each measure)
% remove temperature readings as insufficient datapoints for a number of
% the interventions
if ismember(study, {'SC', 'TM'})
    idx = ismember(measures.DisplayName, {'Temperature'});
    amDatacube(:,:,measures.Index(idx)) = [];
    measures(idx,:) = [];
    nmeasures = size(measures,1);
    measures.Index = (1:nmeasures)';
end
measures = getMeasuresMask(measuresmask, measures);
% calculate the overall & alignment window std for each measure and store in measures
% table. Also the overall min, max and range values by measure (across all
% patients and days)
for m = 1:nmeasures
    tempdata = [];
    for i = 1:ninterventions
        scid   = amInterventions.SmartCareID(i);
        start = amInterventions.IVScaledDateNum(i);
        periodstart = start;
        tempdata = [tempdata; amDatacube(scid, periodstart:(start + align_wind - 1), m)'];
    end
    tempdata(1) = [];
    measures.AlignWindStd(m) = std(tempdata(~isnan(tempdata)));
    tempdata = reshape(amDatacube(:, :, m), npatients * ndays, 1);
    measures.OverallStd(m) = std(tempdata(~isnan(tempdata)));
    [measures.OverallMin(m), measures.OverallMax(m)] = getMeasureOverallMinMax(demographicstable, measures.Name{m});
    measures.OverallRange(m) = measures.OverallMax(m) - measures.OverallMin(m);
end
end