Description of RamEMMCCalcMeanAndStd
Home > Code > pdm > recovery > updatedModel > RamEMMCCalcMeanAndStd.m
RamEMMCCalcMeanAndStd
PURPOSE
amEMMCCalcMeanAndStd - recalc meancurvemean and meancurvestd arrays
SYNOPSIS
function [meancurvemean, meancurvestd] = RamEMMCCalcMeanAndStd(meancurvesumsq, meancurvesum, meancurvecount)
DESCRIPTION
 amEMMCCalcMeanAndStd - recalc meancurvemean and meancurvestd arrays
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
runAlignmentModelEMMCRecoveryFcn runs the alignment model (EM version) given a set of run parameters.
runFastAlignmentModelEMMCRecoveryFcn fast version with 1 plot (typical profile) + alignment result matfile
amEMMCAlignCurvesRecovery amEMMCAlignCurves - function to align measurement curves prior to
SOURCE CODE
function [meancurvemean, meancurvestd] = RamEMMCCalcMeanAndStd(meancurvesumsq, meancurvesum, meancurvecount)
% amEMMCCalcMeanAndStd - recalc meancurvemean and meancurvestd arrays
% recalculate mean curve and std by day
meancurvemean = meancurvesum ./ meancurvecount;
meancurvestd  = (abs((meancurvesumsq ./ meancurvecount) - (meancurvemean .* meancurvemean))) .^ 0.5;
end