Description of init
Home > Code > pdm > FEV1variability > init.m
init
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
setBaseDir setBaseDir - sets the root directory for the code, plots, data files etc
This function is called by:
analyseFEV1Variability analysis of FEV1 variability with moving average manually implemented
plotFEV1profiles plot FEV1 profiles with modulators and treatments
createHeatMapInterventions plot heatmap with #measurements per day for all interventions
exploreInterventions explores the list of interventions
patientCommitment insights about the amount of FEV1 recordings per patient across the study
patientDemographics create an excel with current BR patient demographics
plotPatientProfiles plot a profile of each measures for each patient over the whole enrolment period
analyseModelRobustness analyse the model robustness (classification consistency for various)
analyseVshift used to find the optimal maximum vertical shift value
checkBreatheTreatmentsVsSelectMeasuresPost creates list of oral & IV treatments for recovery study
createAlignmentModelInputsRecovery creates the inputs for the model
findDataAnomaliesRecovery highlight data anomalies to be optionnaly excluded prior to run the alignment model
generateRecoveryCurve plot an unaligned profile
masterScriptRecovery master script to run an alignment model for recovery (post redcap migration)
plotTypicalProfileAndTimeToResponse plot typical profile and compute time to response
relateInferredClassesToPatientFeatures analyse the relation between patient characteristics and subset of interventions
runAlignmentModelEMMCScriptRecovery main script to run alignment models (EMMC versions)
runSpecificInterventions run a model with a manually selected subset of interventions
SOURCE CODE
clear; clc;
% helpers
addpath /Users/tristan.trebaol/Documents/PDM/Project/Code/pdm/helperfunctions/;
addpath /Users/tristan.trebaol/Documents/PDM/Project/Code/smartcare/;
basedir = setBaseDir();
subfolder = 'MatlabSavedVariables';
study = 'BR';
plotfolder = '/Users/tristan.trebaol/Documents/PDM/Project/PlotsFEVAnalysis/';
data_window = 20;
% colors
% cvcol   = [0.94  0.52  0.15];
% admcol  = [0.694 0.627 0.78];
% ivcol   = [1     0     0   ];
% oralcol = [1     0.85  0   ];
% trplcol = [0     1     0   ];
% drugcol = [0     0.8   0.6 ];
% manually add triple therapy start for 501
% manually add predicted FEV1 to 3.69 for 616