Description of amEMMCCalcMeanAndStd
Home > Code > smartcare > amEMMCCalcMeanAndStd.m
amEMMCCalcMeanAndStd
PURPOSE
amEMMCCalcMeanAndStd - recalc meancurvemean and meancurvestd arrays
SYNOPSIS
function [meancurvemean, meancurvestd] = amEMMCCalcMeanAndStd(meancurvesumsq, meancurvesum, meancurvecount, min_offset, max_offset, align_wind)
DESCRIPTION
 amEMMCCalcMeanAndStd - recalc meancurvemean and meancurvestd arrays
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
amEMMCAlignCurves amEMMCAlignCurves - function to align measurement curves prior to
runAlignmentModelEMMCFcn runs the alignment model (EM version) given a set of run parameters.
runAlignmentModelEMMCFcnSplit function to run the alignment model (EM version) given a set of run
testobjfcnscript
SOURCE CODE
function [meancurvemean, meancurvestd] = amEMMCCalcMeanAndStd(meancurvesumsq, meancurvesum, meancurvecount, min_offset, max_offset, align_wind)
% amEMMCCalcMeanAndStd - recalc meancurvemean and meancurvestd arrays
% recalculate mean curve and std by day
meancurvemean = meancurvesum ./ meancurvecount;
meancurvestd  = (abs((meancurvesumsq ./ meancurvecount) - (meancurvemean .* meancurvemean))) .^ 0.5;
if min_offset > 0
    meancurvemean(:, (max_offset + align_wind - min_offset): (max_offset + align_wind - 1),:) = 0;
    meancurvestd(:, (max_offset + align_wind - min_offset): (max_offset + align_wind - 1),:)  = 0;
end
end