Description of amEMAddToMean
Home > Code > smartcare > amEMAddToMean.m
amEMAddToMean
PURPOSE
amEMAddToMean - add an underlying curve to the mean curve (sumsq, sum and count)
SYNOPSIS
function [meancurvesumsq, meancurvesum, meancurvecount] = amEMAddToMean(meancurvesumsq, meancurvesum, meancurvecount,overall_pdoffset, amIntrCube, amHeldBackcube, currinter, min_offset, max_offset, align_wind, nmeasures)
DESCRIPTION
 amEMAddToMean - add an underlying curve to the mean curve (sumsq, sum and count)
 to all possible offsets, weighted by the overall probability of each offset
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
amEMAlignCurves amEMAlignCurves - function to align measurement curves prior to intervention
amEMVisualiseAlignmentDetail amEMVisualiseAlignmentDetail - creates a plot of horizontal bars showing
checkEMLatentCurves
SOURCE CODE
function [meancurvesumsq, meancurvesum, meancurvecount] = amEMAddToMean(meancurvesumsq, meancurvesum, meancurvecount, ...
    overall_pdoffset, amIntrCube, amHeldBackcube, currinter, min_offset, max_offset, align_wind, nmeasures)
% amEMAddToMean - add an underlying curve to the mean curve (sumsq, sum and count)
% to all possible offsets, weighted by the overall probability of each offset
for offset = min_offset:max_offset-1
    % place the current intervention curve into every possible offset
    % position, weighted by the probability each offset position is the
    % right one
    for m = 1:nmeasures
        for i = 1:(max_offset + align_wind - 1 - offset)
            if (~isnan(amIntrCube(currinter, max_offset + align_wind - i, m)) && amHeldBackcube(currinter, max_offset + align_wind - i, m)==0)
                meancurvesumsq(max_offset + align_wind - offset - i, m) = meancurvesumsq(max_offset + align_wind - offset - i, m) + ((amIntrCube(currinter, max_offset + align_wind - i, m) ^ 2) * overall_pdoffset(currinter, offset + 1));
                meancurvesum(max_offset + align_wind - offset - i, m)   = meancurvesum(max_offset + align_wind - offset - i, m)   + (amIntrCube(currinter, max_offset + align_wind - i, m) * overall_pdoffset(currinter, offset + 1));
                meancurvecount(max_offset + align_wind - offset - i, m) = meancurvecount(max_offset + align_wind - offset - i, m) + overall_pdoffset(currinter, offset + 1);
            end
        end
    end
end
end