Description of amEMMCConvertFromLogSpaceAndNormalise
Home > Code > smartcare > amEMMCConvertFromLogSpaceAndNormalise.m
amEMMCConvertFromLogSpaceAndNormalise
PURPOSE
amEMMCConvertFromLogSpaceAndNormalise - takes the results from a 'distance'
SYNOPSIS
function [probdist] = amEMMCConvertFromLogSpaceAndNormalise(distfcn)
DESCRIPTION
 amEMMCConvertFromLogSpaceAndNormalise - takes the results from a 'distance'
 function in log space and normalises to a probability distribution.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
runAlignmentModelEMMCRecoveryFcn runs the alignment model (EM version) given a set of run parameters.
runFastAlignmentModelEMMCRecoveryFcn fast version with 1 plot (typical profile) + alignment result matfile
RamEMMCBestFit amEMMCBestFit - calculates the offset and curve for an intervention by minimising the
RamEMMCInitialiseAlignment amEMMCInitialiseAlignment - function to initialise the various variables
amEMMCBestFit amEMMCBestFit - calculates the offset and curve for an intervention by minimising the
amEMMCInitialiseAlignment amEMMCInitialiseAlignment - function to initialise the various variables
runAlignmentModelEMMCFcn runs the alignment model (EM version) given a set of run parameters.
runAlignmentModelEMMCFcnSplit function to run the alignment model (EM version) given a set of run
SOURCE CODE
function [probdist] = amEMMCConvertFromLogSpaceAndNormalise(distfcn)
% amEMMCConvertFromLogSpaceAndNormalise - takes the results from a 'distance'
% function in log space and normalises to a probability distribution.
probdist = exp(-1 * (distfcn - min(min(distfcn))));
probdist = probdist / sum(sum(probdist));
end