Description of calcRegDist
Home > Code > smartcare > calcRegDist.m
calcRegDist
PURPOSE
calcRegDist - convenience function to calculate the sum of squares
SYNOPSIS
function [dist] = calcRegDist(lcpointmean, lcpointstd, pmstd, datapoint, sigmamethod)
DESCRIPTION
 calcRegDist - convenience function to calculate the sum of squares
 difference for the objective function
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
RamEMMCCalcImputedProbabilities getImputedProbabilities - gets the probabilities for the set of held back
amEMCalcObjFcn amEMCalcObjFcn - calculates residual sum of squares distance for points in
amEMMCCalcImputedProbabilities getImputedProbabilities - gets the probabilities for the set of held back
calcImputedProbabilities getImputedProbabilities - gets the probabilities for the set of held back
SOURCE CODE
function [dist] = calcRegDist(lcpointmean, lcpointstd, pmstd, datapoint, sigmamethod)
% calcRegDist - convenience function to calculate the sum of squares
% difference for the objective function
if sigmamethod == 4
    dist = ( (lcpointmean - datapoint) ^ 2 ) / ( 2 * (lcpointstd ^ 2) ) ...
           + log(lcpointstd) ...
           + log((2 * pi) ^ 0.5);
else
    dist = ( (lcpointmean - datapoint) ^ 2 ) / ( 2 * pmstd ) ...
           + log(pmstd) ...
           + log((2 * pi) ^ 0.5);
end
end