Description of convertFromLogSpaceAndNormalise
Home > Code > smartcare > convertFromLogSpaceAndNormalise.m
convertFromLogSpaceAndNormalise
PURPOSE
convertFromLogSpaceAndNormalise - takes the results from a 'distance'
SYNOPSIS
function [probdist] = convertFromLogSpaceAndNormalise(distfcn)
DESCRIPTION
 convertFromLogSpaceAndNormalise - takes the results from a 'distance'
 function in log space and normalises to a probability distribution.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
amEMAlignCurves amEMAlignCurves - function to align measurement curves prior to intervention
amEMBestFit amEMBestFit - calculates the offset for an intervention by minimising the
runAlignmentModel4
SOURCE CODE
function [probdist] = convertFromLogSpaceAndNormalise(distfcn)
% convertFromLogSpaceAndNormalise - takes the results from a 'distance'
% function in log space and normalises to a probability distribution.
probdist = exp(-1 * (distfcn - min(distfcn)));
probdist = probdist / sum(probdist);
end