Description of createFigureAndPanel
Home > Code > smartcare > createFigureAndPanel.m
createFigureAndPanel
PURPOSE
createFigureAndPanel - creates a figure with a ui panel and returns
SYNOPSIS
function [f, p] = createFigureAndPanel(name, orientation, pagesize)
DESCRIPTION
 createFigureAndPanel - creates a figure with a ui panel and returns
 handles to each
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
amEMPlotAndSaveAlignedCurvesRecovery amEMPlotAndSaveAlignedCurves - plots the curves pre and post alignment for
amEMVisualiseAlignmentDetailRecovery amEMVisualiseAlignmentDetail - creates a plot of horizontal bars showing
am4PlotAndSaveAlignedCurves am4PlotAndSaveAlignedCurves - plots the curves pre and post alignment for
am4PlotsAndSavePredictions am4PlotsAndSavePredictions - plots measures prior to
am4VisualiseAlignmentDetail am4VisualiseAlignmentDetail - creates a plot of horizontal bars showing
amEMMCAnimatedAlignmentConcurrent amEMMCAnimatedAlingmentConcurrent - function to display animated curve
amEMMCAnimatedProbDistConcurrent amEMMCAnimatedProbDistConcurrent - function to display animated
amEMMCCompareModelRunToTestData amEMMCCompareModelRunToTestData - compares the output of a chosen model run to
amEMMCCompareModelRuns
amEMMCCompareModelRunsByLCSets amEMMCCompareModelRunsByLCSets - compares populations of latent curve
amEMMCCompareMultipleModelRunToTestData amEMMCCompareMultipleModelRunToTestData - compares the output of multiple model runs to
amEMMCCompareMultipleModelRunsByLCSets amEMMCCompareMultipleModelRunsByLCSets - compares the the latent curve set populations
amEMMCCreateLabelledInterventions amEMMCCreateLabelledInterventions - plots measurement data and asks for lower
amEMMCPlotAlignedCurvesSideBySide amEMPlotAlignedCurvesSideBySide - for 2 or 3 sets of latent curves, plots
amEMMCPlotFEV1VsLatentCurveSet amEMMCPlotFEV1VsLatentCurveSet - plots the robust FEV1 max vs the latent
amEMMCPlotHistogramOfVShifts amEMMCPlotHistogramOfVShifts - plot a histogram of the vertical shifts
amEMMCPlotInterventionsByLatentCurveSet amEMMCPlotInterventionsByLatentCurveSet - plots interventions and
amEMMCPlotLabelledInterventions amEMMCPlotLabelledInterventions - plots all the labelled test data
amEMMCPlotProbsLCSet amEMMCPlotProbsLCSet - plots the probabilities of respective LC set
amEMMCPlotSingleMeasureByLCSet amEMMCPlotSingleMeasureByLCSet - plots a given measure prior to
amEMMCPlotSuperimposedAlignedCurves amEMMCPlotSuperimposedAlignedCurves - wrapper around the
amEMMCPlotSuperimposedMeasuresB4Intr amEMMCPlotSuperimposedAlignedCurves - wrapper around the
amEMMCPlotVariablesVsLatentCurveSet amEMMCPlotVariablesVsLatentCurveSet - compact plots of various variables
amEMMCPlotsAndSavePredictions amEMMCPlotsAndSavePredictions - plots measures prior to
amEMPlotAndSaveAlignedCurves amEMPlotAndSaveAlignedCurves - plots the curves pre and post alignment for
amEMPlotAndSaveAlignedCurvesBasic amEMPlotAndSaveAlignedCurvesBasic - plots the curves pre and post alignment for
amEMPlotsAndSavePredictions amEMPlotsAndSavePredictions - plots measures prior to
amEMVisualiseAlignmentDetail amEMVisualiseAlignmentDetail - creates a plot of horizontal bars showing
animatedAlignmentConcurrent animatedALingmentConcurrent - function to display animated curve
animatedAlignmentSequential
animatedProbDistConcurrent animatedALingmentConcurrent - function to display animated curve
calcExStartFromTestLabels calcExStartFromTestLabels - derives the ex_start date for a given
cointoss1
cointoss2 set beta prior parameters
compareModelRunToTestData compareModelRunToTestData - compares the output of a chosen model run to
compareModelRuns
compareModelRunsScript
compareMultipleModelRunResults compareMultipleModelRunResults - compares the results of multiple model
compareMultipleModelRunToTestData compareMultipleModelRunToTestData - compares the output of multiple model runs to
createAndSaveBreatheFEVPlots createAndSaveBreatheFEVPlots - function to create plots of FEV home vs clinical
createAndSaveBreatheWeightPlots createAndSaveBreatheWeightPlots - function to create plots of weight home vs clinical
createAndSaveClimbFEVPlots createAndSaveFEVPlots - function to create plots of FEV home vs clinical
createAndSaveWeightPlots createAndSaveWeightPlots - function to create plots of Weight home vs clinical
createHeatmapOfPatientsAndMeasures createHeatmapOfPatientsAndMeasures - given a table of SmartCareID's and
createLabelledInterventions createLabelledInterventions - plots measurement data and asks for lower
createMeasuresHeatmapWithStudyPeriod createMeasuresHeatmapWithStudyPeriod - creates the Patient/Measures
plotLabelledInterventions plotLabelledInterventions - plots all the labelled test data
plotMeasuresByHour plotMeasuresByHour - for each measure, plot a histogram of number of
visualiseMeasures
visualisePatientSummary
SOURCE CODE
function [f, p] = createFigureAndPanel(name, orientation, pagesize)
% createFigureAndPanel - creates a figure with a ui panel and returns
% handles to each
f = figure('Name', name);
%set(gcf, 'Units', 'normalized', 'OuterPosition', [0.65, 0, 0.35, 0.92], 'PaperOrientation', orientation, 'PaperUnits', 'normalized','PaperPosition',[0, 0, 1, 1], 'PaperType', pagesize);
set(gcf, 'Units', 'normalized', 'OuterPosition', [0.65, 0, 0.35, 0.92], 'PaperOrientation', orientation, ...
    'PaperUnits', 'normalized','PaperPosition',[0, 0, 1, 1], 'PaperType', pagesize);
p = uipanel('Parent',f,'BorderType','none', 'BackgroundColor', 'white');
p.Title = name;
p.TitlePosition = 'centertop';
p.FontSize = 8;
p.FontWeight = 'bold';
end