Description of getColumnForMeasure
Home > Code > smartcare > getColumnForMeasure.m
getColumnForMeasure
PURPOSE
getColumnForMeasure - returns the column name from physdata for the
SYNOPSIS
function [column] = getColumnForMeasure(measure)
DESCRIPTION
 getColumnForMeasure - returns the column name from physdata for the
 measure passed in
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
plotPatientProfiles plot a profile of each measures for each patient over the whole enrolment period
findDataAnomaliesRecovery highlight data anomalies to be optionnaly excluded prior to run the alignment model
calculateMuNormalisationRecovery populates an array of ninterventions by nmeasures with the additive
addBreatheRowsForMeasure addBreatheRowsForMeasure - adds the rows to physdata (and
addDupeRows addDupeRows - adds to dupe rows array and relevant index arrays
am2PlotsAndSavePredictions am2PlotsAndSavePredictions - plots measures prior to
am3PlotsAndSavePredictions am3PlotsAndSavePredictions - plots measures prior to
amPlotsAndSavePredictions amPlotsAndSavePredictions - plots measures prior to
analyseStableMeanOptions
calculateMuNormalisation calculateMuNormalisation - - populates an array of ninterventions by
calculateSigmaNormalisation calculateSigmaNormalisation - populates an array of ninterventions by
createInterpMeasure createInterpMeasure - function to add a new measure of interpolated
createMeasuresTable creates the measures table
findAndDeleteAnomalousMeasures findAndDeleteAnomalousMeasures - finds anomalous values and deletes them
findDataAnomalies highlight data anomalies to be optionnaly excluded prior to run the alignment model
getMeasureOverallMinMax getMeasureMinMax - returns the min and max value for a measure across all
loadclimbdata
printDataDemographics printDataDemographics - calculates and prints the count, mean, std, min, max
runAlignmentModel2
runAlignmentModel3
runAlignmentModel4
visualiseExacerbationTimeline
visualiseMeasures
visualiseMeasuresFcn visualiseMeasuresFcn - plots clinical and home measures
visualiseMeasuresForPaperFcn visualiseMeasuresForPaperFcn - plots clinical and home measures
visualiseMeasuresForPaperFcn2 visualiseMeasuresForPaperFcn2 - plots clinical and home measures
visualisePatientSummary
SOURCE CODE
function [column] = getColumnForMeasure(measure)
% getColumnForMeasure - returns the column name from physdata for the
% measure passed in
switch measure
    case 'ActivityRecording'
        column = 'Activity_Steps';
    case {'AppetiteRecording', 'BreathlessnessRecording', 'CoughRecording','SleepActivityRecording', 'SputumVolumeRecording', 'TirednessRecording', 'WellnessRecording'}
        column = 'Rating';
    case 'CalorieRecording'
        column = 'Calories';
    case {'FEV1Recording', 'FEF2575Recording', 'FEV075Recording', 'FEV1DivFEV6Recording', 'FEV6Recording', 'InterpFEV1Recording'}
        column = 'FEV';
    case {'HasColdOrFluRecording', 'HasHayFeverRecording'}
        column = 'HasCondition';
    case 'LungFunctionRecording'
        column = 'CalcFEV1_';
    case {'MinsAsleepRecording', 'MinsAwakeRecording'}
        column = 'Sleep';
    case 'O2SaturationRecording'
        column = 'O2Saturation';
    case {'PulseRateRecording', 'RestingHRRecording'}
        column = 'Pulse_BPM_';
    case 'RespiratoryRateRecording'
        column = 'BreathsPerMin';
    case 'SleepDisturbanceRecording'
        column = 'NumSleepDisturb';
    case {'SputumColorRecording', 'SputumColourRecording'}
        column = 'SputumColour';
    case {'SputumSampleRecording'}
        column = 'SputumSampleTaken_';
    case 'TemperatureRecording'
        column = 'Temp_degC_';
    case {'WeightRecording', 'InterpWeightRecording'}
        column = 'WeightInKg';
    otherwise
        fprintf('*** Unknown measure %s ***\n', measure);
        column = '';
end
end