Description of getExNormMeasures
Home > Code > smartcare > getExNormMeasures.m
getExNormMeasures
PURPOSE
getExNormMeasures - returns an array of measure display names that need
SYNOPSIS
function [exnormmeasarray] = getExNormMeasures(study)
DESCRIPTION
 getExNormMeasures - returns an array of measure display names that need
 to be excluded from normalisation
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
calculateMuNormalisationRecovery populates an array of ninterventions by nmeasures with the additive
calculateMuNormalisation calculateMuNormalisation - - populates an array of ninterventions by
calculateSigmaNormalisation calculateSigmaNormalisation - populates an array of ninterventions by
SOURCE CODE
function [exnormmeasarray] = getExNormMeasures(study)
% getExNormMeasures - returns an array of measure display names that need
% to be excluded from normalisation
if ismember(study, {'BR'})
    exnormmeasarray = {'HasColdOrFlu', 'HasHayFever'};
else
    exnormmeasarray = {''};
end
end