Description of getLatestBreatheDatesForHosp
Home > Code > smartcare > getLatestBreatheDatesForHosp.m
getLatestBreatheDatesForHosp
PURPOSE
getLatestBreatheDatesForHosp - convenience function to centralise getting the
SYNOPSIS
function [clinprocdate, patientmasterdate, isValid] = getLatestBreatheDatesForHosp(hosp)
DESCRIPTION
 getLatestBreatheDatesForHosp - convenience function to centralise getting the
 latest breathe clinical and measurement filename date suffixes for a
 given hospital
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
plotMonthlyBehaviour plots monthly evolution of biomarkers
createBreatheClinicalSpreadsheetsByPatient-DS iMac 201611 (2)
createBreatheClinicalSpreadsheetsByPatient
createBreatheUpdatedMappingFile
createDataExportForREDCap createDataExportForREDCap.m - a script that takes current clinical data
loadPatientMasterFileForAllHosp loadPatientMasterFileForAllHosp - loads and concatenates the patient
loadbreatheclinicaldatanew loads Breathe clinical data for each patient
SOURCE CODE
function [clinprocdate, patientmasterdate, isValid] = getLatestBreatheDatesForHosp(hosp)
% getLatestBreatheDatesForHosp - convenience function to centralise getting the
% latest breathe clinical and measurement filename date suffixes for a
% given hospital
isValid = true;
if (ismember(hosp, 'PAP'))
    clinprocdate      = '20210228';
    patientmasterdate = '20210315';
elseif (ismember(hosp, 'CDF'))
    clinprocdate      = '20210305';
    patientmasterdate = '20210305';
else
    fprintf('**** Unknown Hospital ****/n');
    isValid      = false;
    clinprocdate = '';
    patientmasterdate  = '';
end
end