Description of getLatestFileName
Home > Code > smartcare > getLatestFileName.m
getLatestFileName
PURPOSE
getLatestFileName - returns the name of the most recent version of a file
SYNOPSIS
function [latestfname, filefound] = getLatestFileName(basedir, subfolder, fnamematchstring)
DESCRIPTION
 getLatestFileName - returns the name of the most recent version of a file
 in a given directory matching a particular wildcard string match
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
loadREDCapDataExportFile loadREDCapDataExportFile - loads the latest REDCap data export file
loadREDCapDictionaryFile loadREDCapDictionaryFile - loads the latest REDCap dictionary file
loadREDCapFieldMapFile loadREDCapFieldMapFile - loads the latest REDCap field mapping file
loadREDCapPatientIDMapFile loadREDCapPatientIDMapFile - loads the latest REDCap patient id mapping
SOURCE CODE
function [latestfname, filefound] = getLatestFileName(basedir, subfolder, fnamematchstring)
% getLatestFileName - returns the name of the most recent version of a file
% in a given directory matching a particular wildcard string match
filelisting = dir(fullfile(basedir, subfolder, sprintf('%s', fnamematchstring)));
if size(filelisting, 1) > 0
    filetable = cell2table(struct2cell(filelisting)');
    filetable.fname = filetable.Var1;
    filetable.moddate = filetable.Var3;
    filetable.moddate = datetime(filetable.moddate);
    filetable = filetable(:, {'fname', 'moddate'});
    filetable = sortrows(filetable, {'moddate'}, 'descend');
    latestfname = filetable.fname{1};
    filefound = true;
else
    latestfname = '';
    filefound = false;
end
end