Description of loadPatientMasterFileForHosp
Home > Code > smartcare > loadPatientMasterFileForHosp.m
loadPatientMasterFileForHosp
PURPOSE
loadPatientMasterFileForHosp - convenience function to load the patient
SYNOPSIS
function [hosppatientmaster] = loadPatientMasterFileForHosp(study, hosprow, patientmasterdate)
DESCRIPTION
 loadPatientMasterFileForHosp - convenience function to load the patient
 master file for a given hospital and date
CROSS-REFERENCE INFORMATION
This function calls:
setBaseDir setBaseDir - sets the root directory for the code, plots, data files etc
This function is called by:
createBreatheClinicalSpreadsheetsByPatient
createDataExportForREDCap createDataExportForREDCap.m - a script that takes current clinical data
loadPatientMasterFileForAllHosp loadPatientMasterFileForAllHosp - loads and concatenates the patient
SOURCE CODE
function [hosppatientmaster] = loadPatientMasterFileForHosp(study, hosprow, patientmasterdate)
% loadPatientMasterFileForHosp - convenience function to load the patient
% master file for a given hospital and date
basedir = setBaseDir();
patientmasterfile  = sprintf('PBPatientMaster%s%s.xlsx', hosprow.Acronym{1}, patientmasterdate);
fprintf('Loading patient master file %s\n', patientmasterfile);
dfsubfolder = sprintf('DataFiles/%s/PatientMasterFiles', study);
hosppatientmaster = readtable(fullfile(basedir, dfsubfolder, patientmasterfile));
hosppatientmaster.StudyNumber = lower(hosppatientmaster.StudyNumber);
end