Description of loadAndHarmoniseMeasVars
Home > Code > smartcare > loadAndHarmoniseMeasVars.m
loadAndHarmoniseMeasVars
PURPOSE
loadAndHarmoniseMeasVars - loads raw measurement variables and standardises
SYNOPSIS
function [physdata, offset, physdata_predateoutlierhandling] = loadAndHarmoniseMeasVars(datamatfile, subfolder, study)
DESCRIPTION
 loadAndHarmoniseMeasVars - loads raw measurement variables and standardises
 their naming
CROSS-REFERENCE INFORMATION
This function calls:
setBaseDir setBaseDir - sets the root directory for the code, plots, data files etc
This function is called by:
analyseFEV1Variability analysis of FEV1 variability with moving average manually implemented
analyseFEV1Variability_old analysis of FEV1 variability with smoothing spline and movmean
plotFEV1profiles plot FEV1 profiles with modulators and treatments
plotMonthlyBehaviour plots monthly evolution of biomarkers
createHeatMapInterventions plot heatmap with #measurements per day for all interventions
exploreInterventions explores the list of interventions
patientCommitment Insights about the amount of FEV1 recordings per patient across the study
patientDemographics create an excel with current BR patient demographics
plotPatientProfiles plot a profile of each measures for each patient over the whole enrolment period
checkBreatheTreatmentsVsSelectMeasuresPost creates list of oral & IV treatments for recovery study
createAlignmentModelInputsRecovery creates the inputs for the model
runSpecificInterventions run a model with a manually selected subset of interventions
EmemLungFunctionComparison
JosieQuery
PrePostAnalysisPatientEligibilityScript
calcClinicalInfoForPaper
checkBreatheClinicalVsHomeFEV1Measures
checkBreatheClinicalVsHomeWeightMeasures
checkBreatheTreatmentsVsSelectMeasuresPrior creates list of oral & IV treatments
checkClimbCalculatedClinicalVsHomeFEV1Measures
checkClinicalVsHomeWeightMeasures
checkDatesAdmissionsVsAntibiotics
checkDatesClinicVisitsVsCRPNew
checkDatesClinicVisitsVsPFTNew
checkDatesIVTreatmentsVsMeasurementDate
checkDatesIVTreatmentsVsPatientStudyDate
checkIVTreatmentsVsMeasuresPriorNew creates list of oral & IV treatments
checkStudyDateVsFirstMeasurementDate
createAlignmentModelInputs creates the inputs for the model
createBreatheInterimCheckpointStats
createBreathePrePostStats
createClinMeasPredExcelDataByPatient
extractClinicalAndHomeFEV1Measures
runPlotsForPaperEMMC
visualiseExacerbationTimeline
visualiseMeasures
visualisePatientSummary
SOURCE CODE
function [physdata, offset, physdata_predateoutlierhandling] = loadAndHarmoniseMeasVars(datamatfile, subfolder, study)
% loadAndHarmoniseMeasVars - loads raw measurement variables and standardises
% their naming
tic
basedir = setBaseDir();
fprintf('Loading %s Study Measurement data\n', study);
%physdata_original = [];
if ismember(study, 'SC')
    load(fullfile(basedir, subfolder, datamatfile), 'physdata', 'physdata_predateoutlierhandling', 'offset');
elseif ismember(study, 'TM')
    load(fullfile(basedir, subfolder, datamatfile), 'tmphysdata', 'tmoffset', 'tmphysdata_predateoutlierhandling');
    physdata       = tmphysdata;
    offset         = tmoffset;
    physdata_predateoutlierhandling = tmphysdata_predateoutlierhandling;
elseif ismember(study, 'CL')
    load(fullfile(basedir, subfolder, datamatfile), 'clphysdata', 'cloffset', 'clphysdata_predateoutlierhandling');
    physdata       = clphysdata;
    offset         = cloffset;
    physdata_predateoutlierhandling = clphysdata_predateoutlierhandling;
elseif ismember(study, 'BR')
    load(fullfile(basedir, subfolder, datamatfile), 'brphysdata', 'broffset', 'brphysdata_predateoutlierhandling');
    physdata       = brphysdata;
    offset         = broffset;
    physdata_predateoutlierhandling = brphysdata_predateoutlierhandling;
end
toc
end