Description of mid50max
Home > Code > smartcare > mid50max.m
mid50max
PURPOSE
mid50std - returns the std of the mid 50% data points in x (sorted by
SYNOPSIS
function y = mid50max(x)
DESCRIPTION
 mid50std - returns the std of the mid 50% data points in x (sorted by
 magnitude)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
generateDataDemographicsByPatient
generateDataDemographicsByPatientFn generateDataDemographicsByPatientFn - function that creates data
visualisePatientSummary
SOURCE CODE
function y = mid50max(x)
% mid50std - returns the std of the mid 50% data points in x (sorted by
% magnitude)
x = sort(x, 'ascend');
percentile25 = round(size(x,1) * .25) + 1;
percentile75 = round(size(x,1) * .75);
y = max(x(percentile25:percentile75));
end