Description of plotVerticalLine
Home > Code > smartcare > plotVerticalLine.m
plotVerticalLine
PURPOSE
plotVerticalLine - plots a vertical line
SYNOPSIS
function [xl, yl] = plotVerticalLine(ax, xval, xl, yl, colour, linestyle, linewidth)
DESCRIPTION
 plotVerticalLine - plots a vertical line
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
amEMMCPlotSuperimposedAlignedCurvesForPaper3Recovery amEMMCPlotSuperimposedAlignedCurves3 - wrapper around the
amEMVisualiseAlignmentDetailRecovery amEMVisualiseAlignmentDetail - creates a plot of horizontal bars showing
am4PlotAndSaveAlignedCurves am4PlotAndSaveAlignedCurves - plots the curves pre and post alignment for
am4PlotsAndSavePredictions am4PlotsAndSavePredictions - plots measures prior to
am4VisualiseAlignmentDetail am4VisualiseAlignmentDetail - creates a plot of horizontal bars showing
amEMMCCompareModelRunToTestData amEMMCCompareModelRunToTestData - compares the output of a chosen model run to
amEMMCCompareModelRuns
amEMMCCreateLabelledInterventions amEMMCCreateLabelledInterventions - plots measurement data and asks for lower
amEMMCPlotLabelledInterventions amEMMCPlotLabelledInterventions - plots all the labelled test data
amEMMCPlotSingleMeasureByLCSet amEMMCPlotSingleMeasureByLCSet - plots a given measure prior to
amEMMCPlotSuperimposedAlignedCurvesForPaper2 amEMMCPlotSuperimposedAlignedCurves2 - wrapper around the
amEMMCPlotSuperimposedAlignedCurvesForPaper3 amEMMCPlotSuperimposedAlignedCurves3 - wrapper around the
amEMMCPlotsAndSavePredictions amEMMCPlotsAndSavePredictions - plots measures prior to
amEMPlotAlignedCurve amEMPlotAlignedCurve - plots a latent curve for a given measure (pre and post alignment)
amEMPlotAndSaveAlignedCurvesBasic amEMPlotAndSaveAlignedCurvesBasic - plots the curves pre and post alignment for
amEMPlotsAndSavePredictions amEMPlotsAndSavePredictions - plots measures prior to
amEMVisualiseAlignmentDetail amEMVisualiseAlignmentDetail - creates a plot of horizontal bars showing
compareModelRunToTestData compareModelRunToTestData - compares the output of a chosen model run to
compareModelRuns
compareModelRunsScript
createLabelledInterventions createLabelledInterventions - plots measurement data and asks for lower
plotExStart plotExStart - plots the predicted exacerbation start plus average
plotLabelledInterventions plotLabelledInterventions - plots all the labelled test data
plotSuperimposedAlignedCurves plotSuperimposedAlignedCurves - plots the aligned curves for each of the
plotSuperimposedAlignedCurvesForPaper plotSuperimposedAlignedCurves - plots the aligned curves for each of the
plotSuperimposedMeasuresB4Intr plotSuperimposedMeasuresB4Intr - plots the measures for the period prior
plotSuperimposedMeasuresB4IntrForPaper plotSuperimposedMeasuresB4Intr - plots the measures for the period prior
SOURCE CODE
function [xl, yl] = plotVerticalLine(ax, xval, xl, yl, colour, linestyle, linewidth)
% plotVerticalLine - plots a vertical line
line(ax, [xval xval] , yl, ...
    'Color', colour, ...
    'LineStyle',linestyle, ...
    'LineWidth', linewidth);
xl = [min(min(xval), xl(1)) max(max(xval), xl(2))];
xlim(xl);
end