Description of savePlotInDir
Home > Code > smartcare > savePlotInDir.m
savePlotInDir
PURPOSE
savePlots - saves the figure to png and svp file types in the specified
SYNOPSIS
function savePlotInDir(f, name, subfolder)
DESCRIPTION
 savePlots - saves the figure to png and svp file types in the specified
 subfolder
CROSS-REFERENCE INFORMATION
This function calls:
setBaseDir setBaseDir - sets the root directory for the code, plots, data files etc
This function is called by:
plotPatientProfiles plot a profile of each measures for each patient over the whole enrolment period
amEMMCPlotSuperimposedAlignedCurvesForPaper3Recovery amEMMCPlotSuperimposedAlignedCurves3 - wrapper around the
amEMMCPlotVariablesVsLatentCurveSetForPaperRecovery amEMMCPlotVariablesVsLatentCurveSet - compact plots of various variables
amEMPlotAndSaveAlignedCurvesRecovery amEMPlotAndSaveAlignedCurves - plots the curves pre and post alignment for
amEMVisualiseAlignmentDetailRecovery amEMVisualiseAlignmentDetail - creates a plot of horizontal bars showing
amEMMCCompareModelRunToTestData amEMMCCompareModelRunToTestData - compares the output of a chosen model run to
amEMMCCompareModelRuns
amEMMCCompareModelRunsByLCSets amEMMCCompareModelRunsByLCSets - compares populations of latent curve
amEMMCCompareMultipleModelRunToTestData amEMMCCompareMultipleModelRunToTestData - compares the output of multiple model runs to
amEMMCCompareMultipleModelRunsByLCSets amEMMCCompareMultipleModelRunsByLCSets - compares the the latent curve set populations
amEMMCCreateLabelledInterventions amEMMCCreateLabelledInterventions - plots measurement data and asks for lower
amEMMCPlotAlignedCurvesSideBySide amEMPlotAlignedCurvesSideBySide - for 2 or 3 sets of latent curves, plots
amEMMCPlotFEV1VsLatentCurveSet amEMMCPlotFEV1VsLatentCurveSet - plots the robust FEV1 max vs the latent
amEMMCPlotHistOfTimeSinceLastExacerbation amEMMCPlotHistogramTimeSinceLastExacerbation - function to plot
amEMMCPlotHistogramOfTimeToTreatForPaper amEMMCPlotHistogramOfTimeToTreatForPaper - plots a historgram of the time
amEMMCPlotHistogramOfVShifts amEMMCPlotHistogramOfVShifts - plot a histogram of the vertical shifts
amEMMCPlotInterventionsByLatentCurveSet amEMMCPlotInterventionsByLatentCurveSet - plots interventions and
amEMMCPlotInterventionsByLatentCurveSetForPaper amEMMCPlotInterventionsByLatentCurveSetForPaper - plots interventions and
amEMMCPlotLabelledInterventions amEMMCPlotLabelledInterventions - plots all the labelled test data
amEMMCPlotProbsLCSet amEMMCPlotProbsLCSet - plots the probabilities of respective LC set
amEMMCPlotSingleMeasureByLCSet amEMMCPlotSingleMeasureByLCSet - plots a given measure prior to
amEMMCPlotSuperimposedAlignedCurves amEMMCPlotSuperimposedAlignedCurves - wrapper around the
amEMMCPlotSuperimposedAlignedCurvesForPaper amEMMCPlotSuperimposedAlignedCurves - wrapper around the
amEMMCPlotSuperimposedAlignedCurvesForPaper2 amEMMCPlotSuperimposedAlignedCurves2 - wrapper around the
amEMMCPlotSuperimposedAlignedCurvesForPaper3 amEMMCPlotSuperimposedAlignedCurves3 - wrapper around the
amEMMCPlotSuperimposedMeasuresB4Intr amEMMCPlotSuperimposedAlignedCurves - wrapper around the
amEMMCPlotVariablesVsLatentCurveSet amEMMCPlotVariablesVsLatentCurveSet - compact plots of various variables
amEMMCPlotVariablesVsLatentCurveSetForPaper amEMMCPlotVariablesVsLatentCurveSet - compact plots of various variables
amEMMCPlotsAndSavePredictions amEMMCPlotsAndSavePredictions - plots measures prior to
amEMPlotAndSaveAlignedCurves amEMPlotAndSaveAlignedCurves - plots the curves pre and post alignment for
amEMPlotAndSaveAlignedCurvesBasic amEMPlotAndSaveAlignedCurvesBasic - plots the curves pre and post alignment for
amEMPlotsAndSavePredictions amEMPlotsAndSavePredictions - plots measures prior to
amEMVisualiseAlignmentDetail amEMVisualiseAlignmentDetail - creates a plot of horizontal bars showing
analyseAndHandleDateOutliers analyseAndHandleDateOutliers - function to do the following :-
calcDaysInPeriodWithHistogram calcDaysInPeriodWithHistogram - calculate the days on IV for pre and during
calcExFrequencyByDT calcExFrequencyByDT - function to analyse the frequency of exacerbations
calcExStartFromTestLabels calcExStartFromTestLabels - derives the ex_start date for a given
calcNbrCFTRModInPeriod calcNbrCFTRModInPeriod - calculates how many patients started CFTR
calcPrePostNbrCFTRModInPeriod calcNbrCFTRModInPeriod - calculates how many patients started CFTR
cointoss
cointoss1
cointoss2 set beta prior parameters
compareModelRunToTestData compareModelRunToTestData - compares the output of a chosen model run to
compareModelRuns
compareModelRunsScript
compareMultipleModelRunResults compareMultipleModelRunResults - compares the results of multiple model
compareMultipleModelRunToTestData compareMultipleModelRunToTestData - compares the output of multiple model runs to
createAndSaveBreatheFEVPlots createAndSaveBreatheFEVPlots - function to create plots of FEV home vs clinical
createAndSaveBreatheWeightPlots createAndSaveBreatheWeightPlots - function to create plots of weight home vs clinical
createAndSaveClimbFEVPlots createAndSaveFEVPlots - function to create plots of FEV home vs clinical
createAndSaveFEVPlots createAndSaveFEVPlots - function to create plots of FEV home vs clinical
createAndSaveWeightPlots createAndSaveWeightPlots - function to create plots of Weight home vs clinical
createLabelledInterventions createLabelledInterventions - plots measurement data and asks for lower
createMeasuresHeatmapSorted createMeasuresHeatmapSorted - creates the Patient/Measures
createMeasuresHeatmapSortedForPaper createMeasuresHeatmapSortedForPaper - creates the Patient/Measures
createMeasuresHeatmapWithStudyPeriod createMeasuresHeatmapWithStudyPeriod - creates the Patient/Measures
createMeasuresHeatmapWithStudyPeriodByHospital createMeasuresHeatmapWithStudyPeriod - creates the Patient/Measures
loadbreatheclinicalREDCapdata loads Breathe clinical data from REDCap database
loadbreatheclinicaldatanew loads Breathe clinical data for each patient
plotAlignedCurveComparison
plotLCSetByHospital plotLCSetByHospital - plots barcharts of Latent Curve set by hospital
plotLabelledInterventions plotLabelledInterventions - plots all the labelled test data
plotMeasuresByHour plotMeasuresByHour - for each measure, plot a histogram of number of
plotNbrIntrByPatient plotNbrIntrByPatient - plots bar chart of number of interventions by
plotPointsWithLFitLoop plotPointsWithLFitLoop loops over all relevant patients and produces
visualiseExacerbationForPaperFcn visualiseExacerbationForPaperFcn - plots measures around an exacerbation
visualiseExacerbationForPaperFcn2 visualiseExacerbationForPaperFcn - plots measures around an exacerbation
visualiseExacerbationForPaperFcn3 visualiseExacerbationForPaperFcn3 - plots measures around an exacerbation
visualiseExacerbationTimeline
visualiseHeatmapForStudyPeriod
visualiseMeasures
visualiseMeasuresFcn visualiseMeasuresFcn - plots clinical and home measures
visualiseMeasuresForPaperFcn visualiseMeasuresForPaperFcn - plots clinical and home measures
visualiseMeasuresForPaperFcn2 visualiseMeasuresForPaperFcn2 - plots clinical and home measures
visualisePatientSummary
SOURCE CODE
function savePlotInDir(f, name, subfolder)
% savePlots - saves the figure to png and svp file types in the specified
% subfolder
% save plot
basedir = setBaseDir();
filename = [name '.png'];
saveas(f,fullfile(basedir, subfolder, filename));
% only add in when necessary to save space
%filename = [name '.svg'];
%saveas(f,fullfile(basedir, subfolder, filename));
end