Description of savePlot
Home > Code > smartcare > savePlot.m
savePlot
PURPOSE
savePlots - saves the figure to png and svp file types
SYNOPSIS
function savePlot(f, name)
DESCRIPTION
 savePlots - saves the figure to png and svp file types
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
am4PlotAndSaveAlignedCurves am4PlotAndSaveAlignedCurves - plots the curves pre and post alignment for
am4PlotsAndSavePredictions am4PlotsAndSavePredictions - plots measures prior to
am4VisualiseAlignmentDetail am4VisualiseAlignmentDetail - creates a plot of horizontal bars showing
SOURCE CODE
function savePlot(f, name)
% savePlots - saves the figure to png and svp file types
% save plot
basedir = './';
subfolder = 'Plots';
filename = [name '.png'];
saveas(f,fullfile(basedir, subfolder, filename));
filename = [name '.svg'];
saveas(f,fullfile(basedir, subfolder, filename));
end