Description of selectHospital
Home > Code > smartcare > selectHospital.m
selectHospital
PURPOSE
selectHospital - choose which hospital to run for
SYNOPSIS
function [hosprow, isValid] = selectHospital()
DESCRIPTION
 selectHospital - choose which hospital to run for
CROSS-REFERENCE INFORMATION
This function calls:
getListOfBreatheHospitals getListOfBreatheHospitals - returns a table containing the acronyms
This function is called by:
createBreatheClinicalSpreadsheetsByPatient-DS iMac 201611 (2)
createBreatheClinicalSpreadsheetsByPatient
createBreatheUpdatedMappingFile
SOURCE CODE
function [hosprow, isValid] = selectHospital()
% selectHospital - choose which hospital to run for
isValid = true;
brhosp = getListOfBreatheHospitals();
nhospitals = size(brhosp, 1);
shospnbr = input('Enter Hospital to run for (1 = Papworth, 2 = Cardiff): ', 's');
hospnbr = str2double(shospnbr);
if (isnan(hospnbr) || hospnbr < 1 || hospnbr > nhospitals)
    fprintf('Invalid choice\n');
    hosprow = [];
    isValid = false;
    return;
end
hosprow = brhosp(hospnbr, :);
end