Description of setBaseDir
Home > Code > smartcare > setBaseDir.m
setBaseDir
PURPOSE
setBaseDir - sets the root directory for the code, plots, data files etc
SYNOPSIS
function [basedir] = setBaseDir()
DESCRIPTION
 setBaseDir - sets the root directory for the code, plots, data files etc
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
analyseFEV1Variability_old analysis of FEV1 variability with smoothing spline and movmean
init
plotMonthlyBehaviour plots monthly evolution of biomarkers
init
patientDemographics create an excel with current BR patient demographics
checkBreatheTreatmentsVsSelectMeasuresPost creates list of oral & IV treatments for recovery study
createAlignmentModelInputsRecovery creates the inputs for the model
createIntrNormDataCube create the array with the normalised data for each intervention
findDataAnomaliesRecovery highlight data anomalies to be optionnaly excluded prior to run the alignment model
init
runAlignmentModelEMMCRecoveryFcn runs the alignment model (EM version) given a set of run parameters.
runAlignmentModelEMMCScriptRecovery main script to run alignment models (EMMC versions)
runFastAlignmentModelEMMCRecoveryFcn fast version with 1 plot (typical profile) + alignment result matfile
RamEMMCInitialiseAlignment amEMMCInitialiseAlignment - function to initialise the various variables
amEMMCPlotVariablesVsLatentCurveSetForPaperRecovery amEMMCPlotVariablesVsLatentCurveSet - compact plots of various variables
calculateMuNormalisationRecovery populates an array of ninterventions by nmeasures with the additive
EmemLungFunctionComparison
EmemPredFEV1Query
JosieQuery
Microbiology_script
PrePostAnalysisPatientEligibilityScript
amEMMCCompareModelRunToTestData amEMMCCompareModelRunToTestData - compares the output of a chosen model run to
amEMMCCompareModelRuns
amEMMCCompareModelRunsByLCSets amEMMCCompareModelRunsByLCSets - compares populations of latent curve
amEMMCCompareMultipleModelRunToTestData amEMMCCompareMultipleModelRunToTestData - compares the output of multiple model runs to
amEMMCCompareMultipleModelRunsByLCSets amEMMCCompareMultipleModelRunsByLCSets - compares the the latent curve set populations
amEMMCCreateLabelledInterventions amEMMCCreateLabelledInterventions - plots measurement data and asks for lower
amEMMCInitialiseAlignment amEMMCInitialiseAlignment - function to initialise the various variables
amEMMCPlotVariablesVsLatentCurveSet amEMMCPlotVariablesVsLatentCurveSet - compact plots of various variables
amEMMCPlotVariablesVsLatentCurveSetForPaper amEMMCPlotVariablesVsLatentCurveSet - compact plots of various variables
amEMMCSelectModelRunFromDir amEMMCSelectModelRunFromDir- allows you to load the saved variables from a
analyseAndHandleDateOutliers analyseAndHandleDateOutliers - function to do the following :-
analyseStableMeanOptions
breatheAzureAccess
calcClinicalInfoForPaper
calcExStartFromTestLabels calcExStartFromTestLabels - derives the ex_start date for a given
checkBreatheClinicalVsHomeFEV1Measures
checkBreatheClinicalVsHomeWeightMeasures
checkBreatheTreatmentsVsSelectMeasuresPrior creates list of oral & IV treatments
checkCalculatedClinicalVsHomeFEV1Measures
checkClimbCalculatedClinicalVsHomeFEV1Measures
checkClinicalFEVInconsistencies
checkClinicalVsHomeFEV1Measures
checkClinicalVsHomeFEV1Measures_Telemed
checkClinicalVsHomeWeightMeasures
checkDatesAdmissionsVsAntibiotics
checkDatesClinicVisitsVsCRPNew
checkDatesClinicVisitsVsPFTNew
checkDatesIVTreatmentsVsMeasurementDate
checkDatesIVTreatmentsVsPatientStudyDate
checkIVTreatmentsVsMeasuresPrior
checkIVTreatmentsVsMeasuresPriorNew creates list of oral & IV treatments
checkStudyDateVsFirstMeasurementDate
compareModelRunToTestData compareModelRunToTestData - compares the output of a chosen model run to
compareModelRuns
compareModelRunsScript
compareMultipleModelRunToTestData compareMultipleModelRunToTestData - compares the output of multiple model runs to
correctLabelledTestData
createAlignmentModelInputs creates the inputs for the model
createBreatheClinicalSpreadsheetsByPatient-DS iMac 201611 (2)
createBreatheClinicalSpreadsheetsByPatient
createBreatheInterimCheckpointStats
createBreathePrePostStats
createBreatheUpdatedMappingFile
createClinMeasPredExcelDataByPatient
createCorrectPatientID
createDataExportForREDCap createDataExportForREDCap.m - a script that takes current clinical data
createLabelledInterventionsFromSubset
createLabelledInterventionsFromSuperset
createMeasuresHeatmapSorted createMeasuresHeatmapSorted - creates the Patient/Measures
createMeasuresHeatmapSortedForPaper createMeasuresHeatmapSortedForPaper - creates the Patient/Measures
createMeasuresHeatmapWithStudyPeriod createMeasuresHeatmapWithStudyPeriod - creates the Patient/Measures
createMeasuresHeatmapWithStudyPeriodByHospital createMeasuresHeatmapWithStudyPeriod - creates the Patient/Measures
extractClinicalAndHomeFEV1Measures
findDataAnomalies highlight data anomalies to be optionnaly excluded prior to run the alignment model
generateDataDemographicsByPatientFn generateDataDemographicsByPatientFn - function that creates data
generateDataDemographicsByPatientScript
handleBreatheDuplicateMeasures handleBreatheDuplicateMeasures - Analyse and correct for duplicate measures
handleClimbDuplicateMeasures handleClimbDuplicateMeasures - Analyse and correct for duplicate measures
handleDuplicateMeasures handleDuplicateMeasures - Analyse and correct for duplicate measures
loadAndHarmoniseClinVars loadAndHarmoniseClinVars - loads clinical variables and standardises
loadAndHarmoniseMeasVars loadAndHarmoniseMeasVars - loads raw measurement variables and standardises
loadGUIDFileForHosp loadGUIDFileForHosp - convenience function to load the guid to email
loadPatientMasterFileForHosp loadPatientMasterFileForHosp - convenience function to load the patient
loadTeleMeddata
loadbreatheclinicalREDCapdata loads Breathe clinical data from REDCap database
loadbreatheclinicaldata
loadbreatheclinicaldatanew loads Breathe clinical data for each patient
loadbreathedata 1st Breathe data processing step and analysis from raw measurements
loadbreathemeasurementdata 1st Breathe data processing step and analysis from raw measurements
loadclimbclinicaldata
loadclimbdata
loadclimbexacerbationreasons
loadsmartcaredata
loadupdatedclinicaldata
plotAlignedCurveComparison
plotLCSetByHospital plotLCSetByHospital - plots barcharts of Latent Curve set by hospital
plotMeasuresByHour plotMeasuresByHour - for each measure, plot a histogram of number of
reconcilePatientIDs
runAlignmentModelEM
runAlignmentModelEMFcn function to run the alignment model (EM version) given a set of run
runAlignmentModelEMFcnFEV1Split function to run the alignment model (EM version) given a set of run
runAlignmentModelEMMCFcn runs the alignment model (EM version) given a set of run parameters.
runAlignmentModelEMMCFcnSplit function to run the alignment model (EM version) given a set of run
runAlignmentModelEMMCScript
runAlignmentModelEMMCScriptSplit
runAlignmentModelEMScript
runAlignmentModelEMScriptFEV1Split
runModelUtilityFunctions
runModelUtilityFunctionsEMMC
runPlotsForPaperEMMC
saveLabelledTestDataToExcel
savePlotInDir savePlots - saves the figure to png and svp file types in the specified
savePlotInDirAsSVG savePlots - saves the figure to png and svp file types in the specified
updateBreatheStudyNumber brPatient.StudyEmail{ismember(brPatient.StudyNumber, '4386')} = 'projectb.4386@gmail.com';
visualiseExacerbationForPaperFcn visualiseExacerbationForPaperFcn - plots measures around an exacerbation
visualiseExacerbationForPaperFcn2 visualiseExacerbationForPaperFcn - plots measures around an exacerbation
visualiseExacerbationForPaperFcn3 visualiseExacerbationForPaperFcn3 - plots measures around an exacerbation
visualiseExacerbationTimeline
visualiseHeatmapForStudyPeriod
visualiseMeasures
visualiseMeasuresFcn visualiseMeasuresFcn - plots clinical and home measures
visualiseMeasuresForPaperFcn visualiseMeasuresForPaperFcn - plots clinical and home measures
visualiseMeasuresForPaperFcn2 visualiseMeasuresForPaperFcn2 - plots clinical and home measures
visualisePatientSummary
SOURCE CODE
function [basedir] = setBaseDir()
% setBaseDir - sets the root directory for the code, plots, data files etc
if ismember(computer, {'MACI64'})
    username = getenv('USER');
else
    username = getenv('USERNAME');
end
% basedir = sprintf('/Users/%s/OneDrive - University Of Cambridge/Documents/AlignmentModel/', username);
basedir = '/Users/tristan.trebaol/Documents/PDM/Project/';
end