Description of setYDisplayRange
Home > Code > smartcare > setYDisplayRange.m
setYDisplayRange
PURPOSE
setYDisplayRange - function to scale y axis of plots appropriately
SYNOPSIS
function [roundedrange] = setYDisplayRange(miny, maxy, lowrangelimit)
DESCRIPTION
 setYDisplayRange - function to scale y axis of plots appropriately
CROSS-REFERENCE INFORMATION
This function calls:
roundRangeScaled roundScaled - scale a number appropriate to its magnitude
This function is called by:
plotPatientProfiles plot a profile of each measures for each patient over the whole enrolment period
createAndSaveBreatheFEVPlots createAndSaveBreatheFEVPlots - function to create plots of FEV home vs clinical
createAndSaveBreatheWeightPlots createAndSaveBreatheWeightPlots - function to create plots of weight home vs clinical
createAndSaveClimbFEVPlots createAndSaveFEVPlots - function to create plots of FEV home vs clinical
createAndSaveFEVPlots createAndSaveFEVPlots - function to create plots of FEV home vs clinical
createAndSaveWeightPlots createAndSaveWeightPlots - function to create plots of Weight home vs clinical
visualiseExacerbationForPaperFcn visualiseExacerbationForPaperFcn - plots measures around an exacerbation
visualiseExacerbationForPaperFcn2 visualiseExacerbationForPaperFcn - plots measures around an exacerbation
visualiseExacerbationForPaperFcn3 visualiseExacerbationForPaperFcn3 - plots measures around an exacerbation
visualiseExacerbationTimeline
visualiseMeasures
visualiseMeasuresFcn visualiseMeasuresFcn - plots clinical and home measures
visualiseMeasuresForPaperFcn visualiseMeasuresForPaperFcn - plots clinical and home measures
visualiseMeasuresForPaperFcn2 visualiseMeasuresForPaperFcn2 - plots clinical and home measures
visualisePatientSummary
SOURCE CODE
function [roundedrange] = setYDisplayRange(miny, maxy, lowrangelimit)
% setYDisplayRange - function to scale y axis of plots appropriately
if (maxy - miny) >= lowrangelimit
    %scaledunit = (maxy - miny) * 0.1;
    %ydisplaymin = miny - scaledunit;
    %ydisplaymax = maxy + scaledunit;
    roundedrange = roundRangeScaled(miny, maxy, 'outer');
else
    ydisplaymin = 0.5 * (maxy + miny) - 0.5 * lowrangelimit;
    ydisplaymax = 0.5 * (maxy + miny) + 0.5 * lowrangelimit;
    if ydisplaymin < 0
        ydisplaymax = ydisplaymax - ydisplaymin;
        ydisplaymin = 0;
    end
    roundedrange = roundRangeScaled(ydisplaymin, ydisplaymax, 'outer');
end
%ydisplayrange = [round(ydisplaymin, 1), round(ydisplaymax, 1)];
end