Description of getMeasureTable
Home > Code > pdm > helperfunctions > getMeasureTable.m
getMeasureTable
PURPOSE
returns a table with all data about the specified recording type
SYNOPSIS
function [out] = getMeasureTable(brphysdata,recording_type,category)
DESCRIPTION
 returns a table with all data about the specified recording type
 Input: raw data, recording_type, category of the recording type
 ------
 there are 17 options for the recording type:
     'CalorieRecording'
     'CoughRecording'
     'FEF2575Recording'
     'FEV075Recording'
     'FEV1DivFEV6Recording'
     'FEV1Recording'
     'FEV6Recording'
     'HasColdOrFluRecording'
     'HasHayFeverRecording'
     'MinsAsleepRecording'
     'MinsAwakeRecording'
     'O2SaturationRecording'
     'PulseRateRecording'
     'RestingHRRecording'
     'TemperatureRecording'
     'WeightRecording'
     'WellnessRecording'
 Output: table with all information
 -------
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
analyseFEV1Variability analysis of FEV1 variability with moving average manually implemented
exploreInterventions explores the list of interventions
calcBRFEV1PrctPredicted calculates FEV1 % predicted for each patient with values in Breathe data
SOURCE CODE
function [out] = getMeasureTable(brphysdata,recording_type,category)
% returns a table with all data about the specified recording type
%
% Input: raw data, recording_type, category of the recording type
% ------
% there are 17 options for the recording type:
%     'CalorieRecording'
%     'CoughRecording'
%     'FEF2575Recording'
%     'FEV075Recording'
%     'FEV1DivFEV6Recording'
%     'FEV1Recording'
%     'FEV6Recording'
%     'HasColdOrFluRecording'
%     'HasHayFeverRecording'
%     'MinsAsleepRecording'
%     'MinsAwakeRecording'
%     'O2SaturationRecording'
%     'PulseRateRecording'
%     'RestingHRRecording'
%     'TemperatureRecording'
%     'WeightRecording'
%     'WellnessRecording'
%
% Output: table with all information
% -------
colnames = {'SmartCareID','ScaledDateNum','DateNum',category,'UserName','CaptureType','Date_TimeRecorded'};
out = brphysdata(ismember(brphysdata.RecordingType, recording_type),colnames);
out = renamevars(out,{'SmartCareID', category},{'ID', recording_type});
end